// Minimal Svelte config consumed ONLY by `svelte-check` (see the `typecheck`
// npm script). Its sole job is to exist at the workspace root so svelte-check
// loads this file instead of probing each page's generated `vite.config.ts`
// — vite 5.x lacks the `resolveConfig` export that @sveltejs/load-config
// expects, so that probe throws "vite.resolveConfig is not a function".
//
// The actual build pipeline does NOT use this file: pages are built by Vite
// via the generated per-page `vite.config.ts` (one-line re-export of
// ui_components/_shared/vite.config.base.ts). Authoring/build config is
// generated by awm/gateway/awm/gateway/packages/gen.py — this file is the one
// hand-authored frontend config and is intentionally not generated.
import { vitePreprocess } from '@sveltejs/vite-plugin-svelte';

export default {
  preprocess: vitePreprocess(),
};
