"""Auto-generate room names as adjective-noun pairs.

Word lists ship inside the package at ``awm/services/_room_names_data/`` and
are regenerated by ``awm.scripts.build_room_names`` (idempotent build pipeline
sourced from WordNet + wordfreq, layered with a curation overlay in the
review files at ``data/awm/room_names/{adjectives,nouns}.md``).

The runtime picks an `(adjective, noun)` pair at random; per-word syllables
are capped at 3 in the build script, so every emitted name is ≤6 syllables.
On collision with an existing room the chosen base is suffixed ``-2``…``-9``.
"""

from __future__ import annotations

import random
from pathlib import Path
from typing import Callable

_DIR = Path(__file__).resolve().parent / "_room_names_data"

ADJECTIVES: tuple[str, ...] = tuple((_DIR / "adjectives.txt").read_text().split())
NOUNS: tuple[str, ...] = tuple((_DIR / "nouns.txt").read_text().split())

assert ADJECTIVES and NOUNS, "room-name word lists are empty"
assert all(w.isalpha() and w.islower() for w in ADJECTIVES + NOUNS), \
    "room-name lists contain non-lowercase-alpha entries"

_MAX_GEN_ATTEMPTS = 1000


def generate_candidates(rng: random.Random | None = None):
    """Yield unique adjective-noun pairs sampled lazily.

    Materializing the full Cartesian product is wasteful when the pools
    hold thousands of words each (multi-million pairs). Instead we sample
    on demand with a `seen` set to skip duplicates.
    """
    r = rng or random.Random()
    seen: set[tuple[str, str]] = set()
    while True:
        pair = (r.choice(ADJECTIVES), r.choice(NOUNS))
        if pair in seen:
            continue
        seen.add(pair)
        yield f"{pair[0]}-{pair[1]}"


def pick_unique(exists: Callable[[str], bool],
                rng: random.Random | None = None) -> str:
    """Return an adjective-noun room name that does not already exist.

    On collision append ``-2``, ``-3``, … to the chosen base. ``exists``
    is a predicate the caller wires up to a DB lookup.
    """
    gen = generate_candidates(rng)
    for _ in range(_MAX_GEN_ATTEMPTS):
        base = next(gen)
        if not exists(base):
            return base
        for n in range(2, 10):
            cand = f"{base}-{n}"
            if not exists(cand):
                return cand
    raise RuntimeError(
        "could not allocate a unique room name; consider expanding the pools"
    )
