"""Scope CRUD — create, complete, delete, list, refresh (v1 modular).

A "scope" is represented by a row in the ``agents`` table
(status ∈ allocated|active|retired) within the scopes service's own DB.
All SQL goes through ScopesDAO.

Cross-service: ``scopes._default_context`` previously called
``awm.services.skills.find_by_name`` — that import is replaced by a
graceful fallback hint (skills service is out-of-process; calling it via
gatewayclient is non-essential for context.md generation).

A scope IS the channel: history.md is rendered from ``scope_posts`` with
``kind='journal'`` (in-process via ``awm.scopes.channel``), and the vagrant
session helper subscribes the user to the scope's channel — there is no
separate rooms/messages/session_logs machinery.
"""

from __future__ import annotations

import os
import re as _re
import shutil
import subprocess
import tempfile
import uuid as _uuid
from pathlib import Path

from awm.config import (
    WORKSPACE_ROOT,
    PROJECTS_DIR,
    DATA_DIR,
    SKILLS_DIR,
    GITHUB_USER,
    VAGRANT_PROJECT,
)
from awm.scopes.git_utils import run_git, detect_default_branch
from awm.scopes.dao import ScopesDAO
from awm.scopes.identity import (
    agent_id_for_scope,
    agent_record_for_scope,
    ensure_agent,
    ensure_project,
    project_id_for_name,
    ms_to_iso,
    now_ms,
    retire_agent,
)
from awm.scopes.models import (
    ScopeCreateRequest,
    ScopeUpdateRequest,
    ScopeSyncRequest,
    ScatterGatherResponse,
    ScopeInfo,
    ScopeListResponse,
    ScopeActionResponse,
)
from awm.scopes._validation import validate_name


def _get_awm_dir(repo_dir: Path) -> Path:
    return repo_dir / ".awm"


def _cleanup_worktree(bare_dir: Path, worktree_dir: Path, feature_branch: str) -> None:
    r = run_git(["git", "-C", str(bare_dir), "worktree", "remove", str(worktree_dir), "--force"])
    if r.returncode != 0 and worktree_dir.exists():
        shutil.rmtree(worktree_dir, ignore_errors=True)
    meta_dir = bare_dir / "worktrees" / worktree_dir.name
    if meta_dir.exists():
        shutil.rmtree(meta_dir, ignore_errors=True)
    run_git(["git", "-C", str(bare_dir), "branch", "-D", feature_branch])


def _default_context(project: str, scope: str) -> str:
    """Generate a default .awm/context.md for a new scope.

    Debrief is a native Claude Code skill (~/.claude/skills/debrief/), so the
    context just names it — no skill-service lookup is needed.
    """
    return (
        f"# {project}/{scope}\n\n"
        f"## Startup\n\n"
        f"1. Run `awm_refresh project={project} scope={scope}` to update local history and artifact indexes\n"
        f"2. Read `.awm/history.md` for session history, open issues, and resolved items\n"
        f"3. Read `.awm/artifacts.md` for available data from sibling scopes\n\n"
        f"## Work\n\n"
        f"- Code is in the current directory (this IS the git worktree)\n"
        f"- Project data is at `.awm/data/`\n"
        f"- Reference protocols (git, mamba, etc.) are on disk at `.awm/skills/` if you need them\n"
        f"- Do NOT edit `.awm/history.md` or `.awm/artifacts.md` — use MCP tools\n\n"
        f"## Debrief\n\n"
        f"When the user asks you to debrief (or says \"debrief\"), run the `debrief` skill —\n"
        f"the end-of-session protocol that commits, journals, reconciles artifacts, and refreshes.\n"
    )


def _ensure_project_row(project: str, *, conn=None) -> str:
    bare = PROJECTS_DIR / project / ".bare"
    return ensure_project(project, repo_path=str(bare), conn=conn)


def _row_to_info(row) -> ScopeInfo:
    return ScopeInfo(
        project=row["project_name"] if "project_name" in row.keys() else row["project"],
        scope=row["scope"],
        status=row["status"],
        branch=row["branch"],
        worktree=row["worktree"],
        repo_path=row["worktree"],
        session=row["session"] or 1,
    )


_TAG_RUN_RE = _re.compile(r"<[^>\n]*>")


def _neutralise_title(text: str) -> str:
    """Make an arbitrary string safe to render as a one-line markdown title.

    A journal post with no ``meta.title`` falls back to its raw body, which can
    contain newlines and — when a tool call was mangled in transport — literal
    tool-call tag fragments (``</invoke>``, ``<meta>…</meta>``). Strip tag-like
    runs and collapse whitespace so neither can smuggle markup or break the line
    in the generated ``history.md``. Presentation-only; the stored row is intact.
    """
    text = _TAG_RUN_RE.sub("", text or "")
    text = _re.sub(r"\s+", " ", text).strip()
    return (text[:80] + "…") if len(text) > 80 else text


def _generate_history_md(project: str, scope: str) -> str:
    from awm.scopes.channel import _coerce_meta

    preface = (
        f"<!-- AUTO-GENERATED by AWM. Do NOT edit this file directly.\n"
        f"     To refresh: `awm_refresh project={project} scope={scope}`\n"
        f"     To add lessons: `scope_post kind=journal` (see debrief skill)\n"
        f"     To search: `scope_fetch project={project} kind=journal` -->\n\n"
        f"# Project History: {project}\n\n"
    )

    dao = ScopesDAO()
    siblings = dao.query_all(
        "SELECT a.scope FROM agents a "
        "JOIN projects p ON p.id = a.project_id "
        "WHERE p.name=? AND a.scope!=? AND a.status='active'",
        (project, scope),
    )
    # Journal entries are scope_posts with kind='journal' (a scope IS the
    # channel; the debrief is a self-post). Structured fields live in meta.
    journals = dao.query_all(
        "SELECT id, owner_scope, body, meta, ts FROM scope_posts "
        "WHERE owner_project=? AND kind='journal' "
        "ORDER BY ts DESC LIMIT 50",
        (project,),
    )

    def _parse(row):
        meta = _coerce_meta(row["meta"])
        body = row["body"] or ""
        title = _neutralise_title(meta.get("title") or body)
        return meta, title

    sections = []
    if siblings:
        lines = ["## Active Sibling Scopes\n"]
        for s in siblings:
            lines.append(f"- **{s['scope']}**")
        sections.append("\n".join(lines))

    if journals:
        by_skill: dict[str, list] = {}
        for row in journals:
            meta, _ = _parse(row)
            key = meta.get("skill_path") or "(freeform)"
            by_skill.setdefault(key, []).append(row)
        lines = ["## Journal\n"]
        for skill_key, entries in by_skill.items():
            lines.append(f"### Skill: {skill_key}\n")
            for row in entries[:10]:
                meta, title = _parse(row)
                outcome = f" [{meta['outcome']}]" if meta.get("outcome") else ""
                scope_tag = f" ({row['owner_scope']})" if row["owner_scope"] != scope else ""
                lines.append(f"**[{row['id']}] {title}**{outcome}{scope_tag}")
                if meta.get("deviations"):
                    lines.append(f"- Deviations: {meta['deviations']}")
                if meta.get("suggestions"):
                    lines.append(f"- Suggestions: {meta['suggestions']}")
                lines.append("")
        sections.append("\n".join(lines))

    if not sections:
        sections.append(
            "*No journal entries yet. They appear here after agents post them "
            "via `scope_post kind=journal`.*\n"
        )

    return preface + "\n".join(sections)


def _generate_artifacts_md(project: str, scope: str) -> str:
    preface = (
        f"<!-- AUTO-GENERATED by AWM. Do NOT edit this file directly.\n"
        f"     To refresh: `awm_refresh project={project} scope={scope}`\n"
        f"     To register outputs: `artifact_register project={project} scope={scope} name=\"...\" path=\"...\" artifact_type=...`\n"
        f"     To search: `artifact_search project={project} query=\"...\"` -->\n\n"
        f"# Project Artifacts: {project}\n\n"
    )
    # Artifacts live in a separate dist; we can't query them in-process.
    # Return a static stub — the artifacts service will overwrite this.
    return preface + "*Artifact index is managed by the artifacts service. Use `artifact_register` to add outputs.*\n"


def refresh_history(project: str, scope: str) -> str:
    validate_name(project, kind="project name")
    validate_name(scope, kind="scope name")
    repo_dir = PROJECTS_DIR / project / scope
    awm_dir = _get_awm_dir(repo_dir)
    content = _generate_history_md(project, scope)
    awm_dir.mkdir(parents=True, exist_ok=True)
    (awm_dir / "history.md").write_text(content)
    (awm_dir / "knowledge.md").unlink(missing_ok=True)
    return content


def refresh_artifacts(project: str, scope: str) -> str:
    validate_name(project, kind="project name")
    validate_name(scope, kind="scope name")
    repo_dir = PROJECTS_DIR / project / scope
    awm_dir = _get_awm_dir(repo_dir)
    content = _generate_artifacts_md(project, scope)
    awm_dir.mkdir(parents=True, exist_ok=True)
    (awm_dir / "artifacts.md").write_text(content)
    return content


def awm_refresh(project: str, scope: str) -> dict:
    validate_name(project, kind="project name")
    validate_name(scope, kind="scope name")
    h = refresh_history(project, scope)
    a = refresh_artifacts(project, scope)
    return {
        "message": f"Refreshed .awm/ for {project}/{scope}",
        "history_lines": len(h.splitlines()),
        "artifacts_lines": len(a.splitlines()),
    }


def ensure_vagrant_repo() -> Path:
    """Bootstrap the unified vagrant-scopes bare repo + matching data dirs."""
    from awm.persistence.config_service import get_vagrant_scopes_repo_url

    bare_dir = PROJECTS_DIR / VAGRANT_PROJECT / ".bare"
    project_dir = bare_dir.parent
    project_dir.mkdir(parents=True, exist_ok=True)

    bare_exists = bare_dir.exists()
    if not bare_exists:
        r = run_git(["git", "init", "--bare", str(bare_dir)])
        if r.returncode != 0:
            raise RuntimeError(f"git init --bare failed: {r.stderr}")

    repo_url = get_vagrant_scopes_repo_url()

    if shutil.which("gh"):
        repo_slug = f"{GITHUB_USER}/vagrant-scopes"
        view = run_git(["gh", "repo", "view", repo_slug])
        if view.returncode != 0:
            create = run_git(["gh", "repo", "create", repo_slug, "--private"])
            if create.returncode != 0 and "already exists" not in (create.stderr or ""):
                raise RuntimeError(f"gh repo create failed: {create.stderr}")

    existing = run_git(["git", "-C", str(bare_dir), "remote", "get-url", "origin"])
    if existing.returncode != 0:
        run_git(["git", "-C", str(bare_dir), "remote", "add", "origin", repo_url])
    elif (existing.stdout or "").strip() != repo_url:
        run_git(["git", "-C", str(bare_dir), "remote", "set-url", "origin", repo_url])

    has_main = run_git(["git", "-C", str(bare_dir), "rev-parse", "--verify",
                        "refs/heads/main"])
    if has_main.returncode != 0:
        with tempfile.TemporaryDirectory() as tmp:
            init_dir = Path(tmp) / "init"
            run_git(["git", "clone", str(bare_dir), str(init_dir)])
            run_git(["git", "-C", str(init_dir), "checkout", "-b", "main"])
            run_git(["git", "-C", str(init_dir), "commit", "--allow-empty",
                     "-m", "Initial commit for vagrant-scopes"])
            run_git(["git", "-C", str(init_dir), "push", "origin", "main"])
            if shutil.which("gh"):
                run_git(["git", "-C", str(bare_dir), "push", "origin", "main"])

    run_git(["git", "-C", str(bare_dir), "symbolic-ref", "HEAD", "refs/heads/main"])

    for d in [
        DATA_DIR / VAGRANT_PROJECT / "raw",
        DATA_DIR / VAGRANT_PROJECT / "staged",
    ]:
        d.mkdir(parents=True, exist_ok=True)

    dao = ScopesDAO()
    with dao.transaction() as conn:
        _ensure_project_row(VAGRANT_PROJECT, conn=conn)

    return bare_dir


def _vagrant_scope_name(user_as: str) -> str:
    import re
    bare = user_as.removeprefix("user:") if user_as.startswith("user:") else user_as
    safe = re.sub(r"[^A-Za-z0-9_-]", "-", bare).strip("-")
    return f"{safe}-handler" if safe else "anon-handler"


def vagrant_scope_identifier(user_as: str) -> str:
    return f"{VAGRANT_PROJECT}/{_vagrant_scope_name(user_as)}"


def ensure_vagrant_session(user_as: str) -> tuple[str, str]:
    """Ensure a vagrant scope exists for ``user_as`` and the requesting user is
    subscribed to its channel. A scope IS the channel, so there is no separate
    room. Returns ``(agent_id, scope_key)`` where ``scope_key`` is
    ``'<project>/<scope>'``."""
    scope_name = _vagrant_scope_name(user_as)
    bare_dir = PROJECTS_DIR / VAGRANT_PROJECT / ".bare"
    if not bare_dir.exists():
        raise FileNotFoundError(
            f"Vagrant-scopes repo not initialized at {bare_dir}. "
            f"Run `awm vagrant-init` first."
        )

    agent_id = agent_id_for_scope(VAGRANT_PROJECT, scope_name)
    if agent_id is None:
        create_scope(ScopeCreateRequest(project=VAGRANT_PROJECT, scope=scope_name))
        agent_id = agent_id_for_scope(VAGRANT_PROJECT, scope_name)

    # Subscribe the requesting user to the scope's channel (idempotent).
    try:
        from awm.scopes import channel
        channel.subscribe(VAGRANT_PROJECT, scope_name, user_as)
    except Exception:
        pass
    return agent_id, f"{VAGRANT_PROJECT}/{scope_name}"


_CONTEXT_IMPORT_LINE = "@.awm/context.md"


def _write_scope_opencode_config(awm_dir: Path) -> None:
    import json
    out: dict
    workspace_cfg = WORKSPACE_ROOT / ".awm" / "mcp-opencode.json"
    if workspace_cfg.is_file():
        try:
            out = json.loads(workspace_cfg.read_text())
        except (OSError, json.JSONDecodeError):
            out = {"$schema": "https://opencode.ai/config.json", "mcp": {}}
    else:
        out = {"$schema": "https://opencode.ai/config.json", "mcp": {}}
    instructions: list[str] = []
    workspace_md = WORKSPACE_ROOT / "WORKSPACE.md"
    if workspace_md.is_file():
        instructions.append(str(workspace_md))
    instructions.append(".awm/context.md")
    out["instructions"] = instructions
    awm_dir.mkdir(parents=True, exist_ok=True)
    (awm_dir / "mcp-opencode.json").write_text(json.dumps(out, indent=2) + "\n")


def _is_tracked(worktree_dir: Path, path: str) -> bool:
    res = subprocess.run(
        ["git", "-C", str(worktree_dir), "ls-files", "--error-unmatch", path],
        capture_output=True,
    )
    return res.returncode == 0


def _strip_context_import(text: str) -> tuple[str, bool]:
    lines = text.splitlines(keepends=True)
    changed = False
    while lines and lines[-1].strip() == _CONTEXT_IMPORT_LINE:
        lines.pop()
        changed = True
        if lines and lines[-1].strip() == "":
            lines.pop()
    if not changed:
        return text, False
    new = "".join(lines)
    if new and not new.endswith("\n"):
        new += "\n"
    return new, True


def _heal_worktree(worktree_dir: Path, *, project: str, scope: str, dry_run: bool) -> dict:
    actions: dict[str, str | None] = {
        "import_line": None, "agents_md": None,
        "claude_md": None, "context_md": None,
        "opencode_config": None,
    }

    agents_path = worktree_dir / "AGENTS.md"
    if agents_path.is_file() and not agents_path.is_symlink():
        if _is_tracked(worktree_dir, "AGENTS.md"):
            body = agents_path.read_text()
            new_body, changed = _strip_context_import(body)
            if changed:
                actions["import_line"] = "stripped"
                if not dry_run:
                    agents_path.write_text(new_body)
        else:
            actions["agents_md"] = "deleted:untracked"
            if not dry_run:
                agents_path.unlink()

    claude_path = worktree_dir / "CLAUDE.md"
    if claude_path.is_symlink():
        try:
            target = os.readlink(str(claude_path))
        except OSError:
            target = ""
        if target == "AGENTS.md":
            actions["claude_md"] = "deleted:symlink"
            if not dry_run:
                claude_path.unlink()
        elif not _is_tracked(worktree_dir, "CLAUDE.md"):
            actions["claude_md"] = "deleted:untracked-symlink"
            if not dry_run:
                claude_path.unlink()
    elif claude_path.exists():
        if not _is_tracked(worktree_dir, "CLAUDE.md"):
            actions["claude_md"] = "deleted:untracked"
            if not dry_run:
                claude_path.unlink()

    awm_dir = worktree_dir / ".awm"
    context_path = awm_dir / "context.md"
    if not context_path.exists():
        actions["context_md"] = "created"
        if not dry_run:
            awm_dir.mkdir(parents=True, exist_ok=True)
            context_path.write_text(_default_context(project, scope))

    opencode_cfg = awm_dir / "mcp-opencode.json"
    existing = opencode_cfg.read_text() if opencode_cfg.is_file() else None
    if not dry_run:
        awm_dir.mkdir(parents=True, exist_ok=True)
        _write_scope_opencode_config(awm_dir)
        new = opencode_cfg.read_text()
        if existing is None:
            actions["opencode_config"] = "created"
        elif new != existing:
            actions["opencode_config"] = "rewritten"
    else:
        import json as _json
        workspace_cfg = WORKSPACE_ROOT / ".awm" / "mcp-opencode.json"
        if workspace_cfg.is_file():
            try:
                preview = _json.loads(workspace_cfg.read_text())
            except (OSError, _json.JSONDecodeError):
                preview = {"$schema": "https://opencode.ai/config.json", "mcp": {}}
        else:
            preview = {"$schema": "https://opencode.ai/config.json", "mcp": {}}
        instr: list[str] = []
        wsmd = WORKSPACE_ROOT / "WORKSPACE.md"
        if wsmd.is_file():
            instr.append(str(wsmd))
        instr.append(".awm/context.md")
        preview["instructions"] = instr
        would = _json.dumps(preview, indent=2) + "\n"
        if existing is None:
            actions["opencode_config"] = "would-create"
        elif would != existing:
            actions["opencode_config"] = "would-rewrite"

    return actions


def heal_scopes(project: str | None = None, dry_run: bool = False) -> list[dict]:
    dao = ScopesDAO()
    sql = (
        "SELECT p.name AS project, a.scope, a.worktree "
        "FROM agents a JOIN projects p ON p.id = a.project_id "
        "WHERE a.status IN ('allocated','active')"
    )
    params: list = []
    if project:
        sql += " AND p.name=?"
        params.append(project)
    rows = dao.query_all(sql, params)

    report: list[dict] = []
    for row in rows:
        worktree = Path(row["worktree"])
        if not worktree.exists():
            report.append({
                "project": row["project"], "scope": row["scope"],
                "worktree": str(worktree), "ok": False,
                "error": "worktree missing",
            })
            continue
        try:
            actions = _heal_worktree(
                worktree, project=row["project"], scope=row["scope"],
                dry_run=dry_run,
            )
            report.append({
                "project": row["project"], "scope": row["scope"],
                "worktree": str(worktree), "ok": True,
                "dry_run": dry_run, "actions": actions,
            })
        except OSError as exc:
            report.append({
                "project": row["project"], "scope": row["scope"],
                "worktree": str(worktree), "ok": False,
                "error": f"{type(exc).__name__}: {exc}",
            })
    return report


def create_scope(req: ScopeCreateRequest) -> ScopeActionResponse:
    """Create a new scope: git worktree + .awm/ metadata + agents row."""
    validate_name(req.project, kind="project name")
    validate_name(req.scope, kind="scope name")
    bare_dir = PROJECTS_DIR / req.project / ".bare"
    if not bare_dir.exists():
        if req.project == VAGRANT_PROJECT:
            raise FileNotFoundError(
                f"Vagrant-scopes repo not initialized at {bare_dir}. "
                f"Run `awm vagrant-init` first."
            )
        raise FileNotFoundError(f"Project '{req.project}' not found (expected {bare_dir})")

    from_branch = req.from_branch or detect_default_branch(bare_dir)
    repo_dir = PROJECTS_DIR / req.project / req.scope
    feature_branch = f"feat/{req.scope}"

    dao = ScopesDAO()
    with dao.transaction() as conn:
        _ensure_project_row(req.project, conn=conn)
        prior = ScopesDAO(conn=conn).query_one(
            "SELECT COUNT(*) AS n FROM agents a "
            "JOIN projects p ON p.id = a.project_id "
            "WHERE p.name=? AND a.scope=?",
            (req.project, req.scope),
        )
        session_num = (prior["n"] or 0) + 1 if prior else 1
        active = agent_id_for_scope(req.project, req.scope, conn=conn, active_only=True)
        if active:
            raise FileExistsError(
                f"Scope '{req.scope}' already has an active session in project '{req.project}'"
            )

    if repo_dir.exists():
        _cleanup_worktree(bare_dir, repo_dir, feature_branch)

    r = run_git(["git", "-C", str(bare_dir), "worktree", "add",
                 f"../{req.scope}", "-b", feature_branch, from_branch])
    if r.returncode != 0:
        raise RuntimeError(f"Failed to create worktree: {r.stderr}")

    awm_dir = _get_awm_dir(repo_dir)
    awm_dir.mkdir(parents=True, exist_ok=True)

    data_link = awm_dir / "data"
    if data_link.is_symlink() or data_link.exists():
        data_link.unlink()
    data_target = DATA_DIR / req.project
    data_target.mkdir(parents=True, exist_ok=True)
    data_link.symlink_to(data_target)

    skills_link = awm_dir / "skills"
    if skills_link.is_symlink() or skills_link.exists():
        skills_link.unlink()
    skills_link.symlink_to(SKILLS_DIR)

    context_content = req.context or _default_context(req.project, req.scope)
    (awm_dir / "context.md").write_text(context_content)
    (awm_dir / "history.md").write_text(_generate_history_md(req.project, req.scope))
    (awm_dir / "artifacts.md").write_text(_generate_artifacts_md(req.project, req.scope))
    _write_scope_opencode_config(awm_dir)

    dao2 = ScopesDAO()
    with dao2.transaction() as conn:
        ensure_agent(
            req.project, req.scope,
            branch=feature_branch,
            worktree=str(repo_dir),
            agent_cli="claude",
            status="allocated",
            is_vagrant=(req.project == VAGRANT_PROJECT),
            conn=conn,
        )

    # Embeddings index
    try:
        from awm.persistence.embeddings import upsert_embedding
        from awm.persistence.databases import get_connection
        text = f"{req.project}/{req.scope} {context_content[:500]}"
        conn = get_connection("scopes")
        try:
            upsert_embedding(conn, "scope", f"{req.project}/{req.scope}", text[:500])
        finally:
            conn.close()
    except Exception:
        pass

    return ScopeActionResponse(
        project=req.project,
        scope=req.scope,
        status="active",
        session=session_num,
        message=(
            f"Created scope at projects/{req.project}/{req.scope} (.awm/ initialized) "
            f"on branch {feature_branch}, session {session_num}"
        ),
    )


def repair_scope(project: str, scope: str) -> ScopeActionResponse:
    """Reconcile an on-disk worktree+.awm/ with a missing DB row."""
    validate_name(project, kind="project name")
    validate_name(scope, kind="scope name")

    bare_dir = PROJECTS_DIR / project / ".bare"
    if not bare_dir.exists():
        raise FileNotFoundError(
            f"Project '{project}' has no bare repo at {bare_dir} — nothing to repair against"
        )

    repo_dir = PROJECTS_DIR / project / scope
    if not repo_dir.is_dir():
        raise FileNotFoundError(f"Worktree not found at {repo_dir}")
    awm_dir = _get_awm_dir(repo_dir)
    context_path = awm_dir / "context.md"
    if not context_path.exists():
        raise FileNotFoundError(
            f"No .awm/context.md at {context_path} — refusing to repair "
            f"a worktree that wasn't initialized by scope_create"
        )

    r = run_git(["git", "-C", str(repo_dir), "branch", "--show-current"])
    branch = (r.stdout or "").strip()
    if r.returncode != 0 or not branch:
        raise RuntimeError(
            f"Could not read branch from worktree {repo_dir}: {r.stderr or 'empty branch name'}"
        )

    dao = ScopesDAO()
    with dao.transaction() as conn:
        _ensure_project_row(project, conn=conn)
        existing = agent_id_for_scope(project, scope, conn=conn, active_only=True)
        if existing:
            return ScopeActionResponse(
                project=project,
                scope=scope,
                status="skipped",
                message=(
                    f"Scope {project}/{scope} already has an active agent row "
                    f"({existing}); nothing to repair"
                ),
            )
        aid = ensure_agent(
            project, scope,
            branch=branch,
            worktree=str(repo_dir),
            agent_cli="claude",
            status="allocated",
            is_vagrant=(project == VAGRANT_PROJECT),
            conn=conn,
        )

    try:
        from awm.persistence.embeddings import upsert_embedding
        from awm.persistence.databases import get_connection
        text = f"{project}/{scope}"
        conn = get_connection("scopes")
        try:
            upsert_embedding(conn, "scope", f"{project}/{scope}", text)
        finally:
            conn.close()
    except Exception:
        pass

    return ScopeActionResponse(
        project=project,
        scope=scope,
        status="repaired",
        message=(
            f"Backfilled agents row for {project}/{scope} from on-disk worktree "
            f"({repo_dir}) on branch {branch}, agent_id={aid}"
        ),
    )


def update_scope(project: str, scope: str, req: ScopeUpdateRequest) -> ScopeActionResponse:
    """Complete a scope (mark agent retired). Optionally merges + cleans up."""
    validate_name(project, kind="project name")
    validate_name(scope, kind="scope name")
    bare_dir = PROJECTS_DIR / project / ".bare"
    repo_dir = PROJECTS_DIR / project / scope

    if not bare_dir.exists():
        raise FileNotFoundError(f"Bare repository not found at {bare_dir}")

    feature_branch = f"feat/{scope}"

    if req.action != "complete":
        raise ValueError(f"Unknown action: {req.action}. Only 'complete' is supported.")

    aid = agent_id_for_scope(project, scope, active_only=True)
    if aid:
        retire_agent(aid)

    merge_msg = ""
    if req.merge:
        default_branch = detect_default_branch(bare_dir)
        main_worktree = PROJECTS_DIR / project / default_branch
        if not main_worktree.exists():
            raise FileNotFoundError(f"Main worktree not found at {main_worktree}")
        run_git(["git", "-C", str(main_worktree), "checkout", default_branch])
        r = run_git(["git", "-C", str(main_worktree), "merge", feature_branch,
                     "-m", f"Merge {feature_branch} into {default_branch}"])
        if r.returncode != 0:
            raise RuntimeError(f"Merge failed: {r.stderr}")
        run_git(["git", "-C", str(main_worktree), "push"])
        merge_msg = f", merged into {default_branch}"

    if req.cleanup:
        _cleanup_worktree(bare_dir, repo_dir, feature_branch)

    return ScopeActionResponse(
        project=project, scope=scope, status="completed",
        message=f"Scope completed{merge_msg}",
    )


def sync_scope(project: str, scope: str, req: ScopeSyncRequest) -> ScopeActionResponse:
    validate_name(project, kind="project name")
    validate_name(scope, kind="scope name")
    bare_dir = PROJECTS_DIR / project / ".bare"
    repo_dir = PROJECTS_DIR / project / scope
    feature_branch = f"feat/{scope}"

    if not bare_dir.exists():
        raise FileNotFoundError(f"Bare repository not found at {bare_dir}")
    if not repo_dir.exists():
        raise FileNotFoundError(f"Worktree not found at {repo_dir}")

    base = req.from_branch or detect_default_branch(bare_dir)

    aid = agent_id_for_scope(project, scope, active_only=True)
    if aid is None:
        raise FileNotFoundError(f"No active scope '{scope}' found in project '{project}'")

    r = run_git(["git", "-C", str(repo_dir), "status", "--porcelain"])
    if r.returncode != 0:
        raise RuntimeError(f"git status failed: {r.stderr}")
    if r.stdout.strip():
        raise RuntimeError(
            f"Worktree has uncommitted changes — refusing to sync:\n{r.stdout}"
        )

    r = run_git(["git", "-C", str(repo_dir), "rev-parse", "--abbrev-ref", "HEAD"])
    if r.returncode != 0:
        raise RuntimeError(f"git rev-parse failed: {r.stderr}")
    current = r.stdout.strip()
    if current != feature_branch:
        raise RuntimeError(
            f"Worktree HEAD is on '{current}', expected '{feature_branch}'. "
            f"Check out the feature branch before syncing."
        )

    if req.strategy == "merge":
        r = run_git([
            "git", "-C", str(repo_dir), "merge", base,
            "-m", f"Sync {base} into {feature_branch}",
        ])
    else:
        r = run_git(["git", "-C", str(repo_dir), "rebase", base])

    if r.returncode != 0:
        raise RuntimeError(
            f"{req.strategy} failed: {r.stderr or r.stdout}\n"
            f"Worktree left mid-{req.strategy}; resolve and re-run, "
            f"or `git {req.strategy} --abort` to undo."
        )

    return ScopeActionResponse(
        project=project,
        scope=scope,
        status="active",
        message=f"Synced {feature_branch} with {base} via {req.strategy}",
    )


def _has_merge_in_progress(worktree: Path) -> bool:
    """True iff a merge is mid-flight (MERGE_HEAD present) in ``worktree``."""
    r = run_git(["git", "-C", str(worktree), "rev-parse", "--verify", "-q", "MERGE_HEAD"])
    return r.returncode == 0


def _merge_one(worktree: Path, scope: str, branch: str, source_ref: str,
               message: str) -> dict:
    """Merge ``source_ref`` into the branch checked out at ``worktree``.

    Batch-safe: on a conflict the merge is rolled back with ``git merge
    --abort`` (only when a merge is actually in progress, so an "Already up to
    date" / fast-forward is never misclassified) and the worktree is left
    clean. Returns ``{scope, branch, result, detail}`` with ``result`` ∈
    ``merged | up_to_date | conflict | error``.
    """
    r = run_git(["git", "-C", str(worktree), "merge", source_ref, "-m", message])
    out = (r.stdout or "") + (r.stderr or "")
    if r.returncode == 0:
        if "Already up to date" in out:
            return {"scope": scope, "branch": branch, "result": "up_to_date",
                    "detail": "already up to date"}
        return {"scope": scope, "branch": branch, "result": "merged",
                "detail": out.strip().splitlines()[-1] if out.strip() else "merged"}
    # Non-zero: a real conflict (or other merge failure). Roll back only when a
    # merge is genuinely in progress, else we'd misreport a no-op/FF as a failed
    # abort and could leave a stray MERGE_HEAD (see MERGE_HEAD-lingers footgun).
    if _has_merge_in_progress(worktree):
        run_git(["git", "-C", str(worktree), "merge", "--abort"])
        return {"scope": scope, "branch": branch, "result": "conflict",
                "detail": "merge conflict — aborted, worktree left clean"}
    return {"scope": scope, "branch": branch, "result": "error",
            "detail": (r.stderr or out).strip()}


def _hub_record(project: str, hub: str, bare_dir: Path) -> dict:
    """Resolve the hub scope's DB row (branch + worktree). Falls back to
    ``feat/<hub>`` / ``PROJECTS_DIR/project/hub`` if no row exists — but a hub
    is normally a real scope, so the row is the authoritative source for legacy
    flat branches like ``dev`` (branch ``dev``, not ``feat/dev``)."""
    rec = agent_record_for_scope(project, hub, active_only=False)
    if rec is not None:
        return {"branch": rec["branch"], "worktree": Path(rec["worktree"])}
    return {"branch": f"feat/{hub}", "worktree": PROJECTS_DIR / project / hub}


def _peripheral_record(project: str, p: str) -> dict:
    """Resolve a peripheral scope's branch + worktree (DB row, else default)."""
    rec = agent_record_for_scope(project, p, active_only=False)
    if rec is not None:
        return {"branch": rec["branch"], "worktree": Path(rec["worktree"])}
    return {"branch": f"feat/{p}", "worktree": PROJECTS_DIR / project / p}


def _summarize(results: list[dict]) -> dict:
    summary: dict[str, int] = {}
    for r in results:
        summary[r["result"]] = summary.get(r["result"], 0) + 1
    return summary


def gather_scope(project: str, hub: str, peripherals: list[str],
                 strategy: str = "merge") -> ScatterGatherResponse:
    """Fan-in: merge each peripheral's branch into the hub's branch.

    Runs in the hub's worktree. The hub worktree must be clean and on the hub
    branch (the whole fan-in needs a clean hub). A per-peripheral conflict is
    aborted and reported; the batch continues. Local-only — no push.
    """
    validate_name(project, kind="project name")
    validate_name(hub, kind="scope name")
    if strategy != "merge":
        raise ValueError("gather only supports strategy='merge' (rebase is not "
                         "meaningful for a shared hub).")
    bare_dir = PROJECTS_DIR / project / ".bare"
    if not bare_dir.exists():
        raise FileNotFoundError(f"Bare repository not found at {bare_dir}")

    hub_rec = _hub_record(project, hub, bare_dir)
    hub_branch = hub_rec["branch"]
    hub_worktree = hub_rec["worktree"]
    if not hub_worktree.exists():
        raise FileNotFoundError(f"Hub worktree not found at {hub_worktree}")

    r = run_git(["git", "-C", str(hub_worktree), "status", "--porcelain"])
    if r.returncode != 0:
        raise RuntimeError(f"git status failed in hub worktree: {r.stderr}")
    if r.stdout.strip():
        raise RuntimeError(
            f"Hub worktree {hub_worktree} has uncommitted changes — refusing to "
            f"gather:\n{r.stdout}"
        )
    r = run_git(["git", "-C", str(hub_worktree), "rev-parse", "--abbrev-ref", "HEAD"])
    current = (r.stdout or "").strip()
    if current != hub_branch:
        raise RuntimeError(
            f"Hub worktree HEAD is on '{current}', expected hub branch "
            f"'{hub_branch}'. Check out the hub branch before gathering."
        )

    results: list[dict] = []
    for p in peripherals:
        validate_name(p, kind="scope name")
        prec = _peripheral_record(project, p)
        p_branch = prec["branch"]
        verify = run_git(["git", "-C", str(bare_dir), "rev-parse", "--verify",
                          "-q", f"refs/heads/{p_branch}"])
        if verify.returncode != 0:
            results.append({"scope": p, "branch": p_branch, "result": "skipped",
                            "detail": f"branch {p_branch} not found"})
            continue
        results.append(_merge_one(
            hub_worktree, p, p_branch, p_branch,
            f"Gather {p_branch} into {hub_branch}",
        ))

    return ScatterGatherResponse(
        project=project, hub=hub, hub_branch=hub_branch, direction="gather",
        results=results, summary=_summarize(results),
    )


def scatter_scope(project: str, hub: str, peripherals: list[str],
                  strategy: str = "merge") -> ScatterGatherResponse:
    """Fan-out: merge the hub's branch into each peripheral's branch.

    Each merge runs in that peripheral's own worktree. A dirty or off-branch
    peripheral is skipped (one dirty sibling must not abort the batch); a
    conflict is aborted and reported. Local-only — no push.
    """
    validate_name(project, kind="project name")
    validate_name(hub, kind="scope name")
    if strategy != "merge":
        raise ValueError("scatter only supports strategy='merge' (rebase is not "
                         "meaningful for fan-out).")
    bare_dir = PROJECTS_DIR / project / ".bare"
    if not bare_dir.exists():
        raise FileNotFoundError(f"Bare repository not found at {bare_dir}")

    hub_rec = _hub_record(project, hub, bare_dir)
    hub_branch = hub_rec["branch"]
    verify = run_git(["git", "-C", str(bare_dir), "rev-parse", "--verify",
                      "-q", f"refs/heads/{hub_branch}"])
    if verify.returncode != 0:
        raise FileNotFoundError(f"Hub branch '{hub_branch}' not found")

    results: list[dict] = []
    for p in peripherals:
        validate_name(p, kind="scope name")
        prec = _peripheral_record(project, p)
        p_branch = prec["branch"]
        p_worktree = prec["worktree"]
        if not p_worktree.exists():
            results.append({"scope": p, "branch": p_branch, "result": "skipped",
                            "detail": f"worktree not found at {p_worktree}"})
            continue
        r = run_git(["git", "-C", str(p_worktree), "status", "--porcelain"])
        if r.returncode != 0 or r.stdout.strip():
            results.append({"scope": p, "branch": p_branch, "result": "skipped",
                            "detail": "worktree dirty — skipped"})
            continue
        r = run_git(["git", "-C", str(p_worktree), "rev-parse", "--abbrev-ref", "HEAD"])
        current = (r.stdout or "").strip()
        if current != p_branch:
            results.append({"scope": p, "branch": p_branch, "result": "skipped",
                            "detail": f"HEAD on '{current}', expected '{p_branch}'"})
            continue
        results.append(_merge_one(
            p_worktree, p, p_branch, hub_branch,
            f"Scatter {hub_branch} into {p_branch}",
        ))

    return ScatterGatherResponse(
        project=project, hub=hub, hub_branch=hub_branch, direction="scatter",
        results=results, summary=_summarize(results),
    )


def delete_scope(project: str, scope: str) -> ScopeActionResponse:
    validate_name(project, kind="project name")
    validate_name(scope, kind="scope name")
    bare_dir = PROJECTS_DIR / project / ".bare"
    repo_dir = PROJECTS_DIR / project / scope
    feature_branch = f"feat/{scope}"

    if not bare_dir.exists():
        raise FileNotFoundError(f"Bare repository not found at {bare_dir}")

    dao = ScopesDAO()
    aid_row = dao.query_one(
        "SELECT a.id, a.status FROM agents a "
        "JOIN projects p ON p.id = a.project_id "
        "WHERE p.name=? AND a.scope=? "
        "AND a.status IN ('allocated','active','retired') "
        "ORDER BY a.created_at DESC LIMIT 1",
        (project, scope),
    )
    if aid_row is None:
        raise FileNotFoundError(f"No scope '{scope}' found in project '{project}'")

    _cleanup_worktree(bare_dir, repo_dir, feature_branch)

    with dao.transaction() as conn:
        ScopesDAO(conn=conn).execute(
            "UPDATE agents SET status='retired', retired_at=? WHERE id=?",
            (now_ms(), aid_row["id"]),
        )

    try:
        from awm.persistence.embeddings import delete_embedding
        from awm.persistence.databases import get_connection
        conn = get_connection("scopes")
        try:
            delete_embedding(conn, "scope", f"{project}/{scope}")
        finally:
            conn.close()
    except Exception:
        pass

    return ScopeActionResponse(
        project=project, scope=scope, status="deleted",
        message="Scope deleted, worktree and branch cleaned up",
    )


def _v37_render_scope(r, session: int = 1) -> ScopeInfo:
    status_render = (
        "active" if r["status"] in ("allocated", "active")
        else ("completed" if r["status"] == "retired" else r["status"])
    )
    return ScopeInfo(
        project=r["project_name"], scope=r["scope"], status=status_render,
        branch=r["branch"], worktree=r["worktree"],
        repo_path=r["worktree"], session=session,
    )


def search_scopes(
    query: str | None = None,
    status: str = "active",
    project: str | None = None,
    limit: int = 50,
    offset: int = 0,
) -> ScopeListResponse:
    """Search scopes. Defaults to status='active'."""
    dao = ScopesDAO()
    sql = (
        "SELECT a.id, a.scope, a.status, a.branch, a.worktree, "
        "       a.created_at, p.name AS project_name, "
        "       (SELECT COUNT(*) FROM agents a2 "
        "        JOIN projects p2 ON p2.id = a2.project_id "
        "        WHERE p2.name = p.name AND a2.scope = a.scope "
        "        AND a2.created_at <= a.created_at) AS session "
        "FROM agents a JOIN projects p ON p.id = a.project_id "
        "WHERE 1=1"
    )
    params: list = []
    if status and status != "all":
        if status == "active":
            sql += " AND a.status IN ('allocated','active')"
        elif status == "completed":
            sql += " AND a.status='retired'"
        elif status == "deleted":
            return ScopeListResponse(scopes=[], total=0)
        else:
            sql += " AND a.status = ?"
            params.append(status)
    if project:
        sql += " AND p.name = ?"
        params.append(project)
    if query:
        sql += " AND a.scope LIKE ?"
        params.append(f"%{query}%")
    sql += " ORDER BY p.name, a.scope LIMIT ? OFFSET ?"
    params.extend([limit, offset])
    rows = dao.query_all(sql, params)

    keyword_hits = [_v37_render_scope(r, session=r["session"] or 1) for r in rows]

    if not query:
        return ScopeListResponse(scopes=keyword_hits, total=len(keyword_hits))

    keyword_keys = {f"{s.project}/{s.scope}" for s in keyword_hits}

    def _materialize(source_id: str):
        if "/" not in source_id:
            return None
        proj, scp = source_id.split("/", 1)
        if project and proj != project:
            return None
        d = ScopesDAO()
        extra_sql = (
            "SELECT a.id, a.scope, a.status, a.branch, a.worktree, "
            "       a.created_at, p.name AS project_name, "
            "       (SELECT COUNT(*) FROM agents a2 "
            "        JOIN projects p2 ON p2.id = a2.project_id "
            "        WHERE p2.name = p.name AND a2.scope = a.scope "
            "        AND a2.created_at <= a.created_at) AS session "
            "FROM agents a JOIN projects p ON p.id = a.project_id "
            "WHERE p.name=? AND a.scope=?"
        )
        extra_params: list = [proj, scp]
        if status and status != "all":
            if status == "active":
                extra_sql += " AND a.status IN ('allocated','active')"
            elif status == "completed":
                extra_sql += " AND a.status='retired'"
            elif status == "deleted":
                return None
            else:
                extra_sql += " AND a.status = ?"
                extra_params.append(status)
        row = d.query_one(extra_sql, extra_params)
        return _v37_render_scope(row, session=row["session"] or 1) if row else None

    try:
        from awm.persistence.embeddings import hybrid_augment
        from awm.persistence.databases import get_connection
        conn = get_connection("scopes")
        try:
            merged = hybrid_augment(
                conn, query,
                source_type="scope",
                keyword_hits=keyword_hits, keyword_keys=keyword_keys,
                materialize=_materialize,
            )
        finally:
            conn.close()
    except Exception:
        merged = keyword_hits
    return ScopeListResponse(scopes=merged, total=len(merged))
