"""Scope CRUD — create, complete, delete, list, refresh."""

from __future__ import annotations

import os
import shutil
import subprocess
import tempfile
from datetime import datetime, timezone
from pathlib import Path

from awm.config import (
    WORKSPACE_ROOT,
    PROJECTS_DIR,
    DATA_DIR,
    SKILLS_DIR,
    GITHUB_USER,
    VAGRANT_PROJECT,
)
from awm.db import get_connection
from awm.git_utils import run_git, detect_default_branch
from awm.models import (
    ScopeCreateRequest,
    ScopeUpdateRequest,
    ScopeSyncRequest,
    ScopeInfo,
    ScopeListResponse,
    ScopeActionResponse,
)
from awm.services._validation import validate_name
from awm.services.replication.schema import new_uuid, next_legacy_id


def _local_peer_id() -> str:
    """Return the local peer id, or '' if PEER_FILE hasn't been initialized.
    Used to stamp origin_peer on new scope rows so post-replication peers
    can identify which peer minted each row."""
    try:
        from awm.services.network.peers import get_local_identity
        ident = get_local_identity()
    except Exception:
        return ""
    if ident is None:
        return ""
    return ident.get("peer_id") or ""


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def _get_awm_dir(repo_dir: Path) -> Path:
    """Return the .awm/ metadata directory inside a scope worktree."""
    return repo_dir / ".awm"


def _cleanup_worktree(bare_dir: Path, worktree_dir: Path, feature_branch: str) -> None:
    """Remove a scope's worktree and branch, ignoring errors."""
    r = run_git(["git", "-C", str(bare_dir), "worktree", "remove", str(worktree_dir), "--force"])
    if r.returncode != 0 and worktree_dir.exists():
        shutil.rmtree(worktree_dir, ignore_errors=True)
    # Only remove the target's metadata dir. NEVER run a blanket
    # `git worktree prune` here: under the .bare layout git sometimes flags
    # healthy sibling worktrees as prunable due to path-resolution quirks, and
    # a blanket prune will wipe their `.bare/worktrees/<name>/` metadata too,
    # leaving dangling `.git` gitlinks in their working directories. See
    # inbox #111 (2026-04-05).
    meta_dir = bare_dir / "worktrees" / worktree_dir.name
    if meta_dir.exists():
        shutil.rmtree(meta_dir, ignore_errors=True)
    run_git(["git", "-C", str(bare_dir), "branch", "-D", feature_branch])


def _default_context(project: str, scope: str) -> str:
    """Generate the default context.md content for a new scope."""
    # Resolve the debrief skill by frontmatter name, not hardcoded path, so the
    # generated context.md stays correct if the skill moves.
    from awm.services.skills import find_by_name
    debrief = find_by_name("debrief")
    debrief_hint = (
        f"`skills_get path=\"{debrief.file_path}\"`"
        if debrief
        else "`skills_search query=\"debrief\"`"
    )
    return (
        f"# {project}/{scope}\n\n"
        f"## Startup\n\n"
        f"1. Run `awm_refresh project={project} scope={scope}` to update local history and artifact indexes\n"
        f"2. Read `.awm/history.md` for session history, open issues, and resolved items\n"
        f"3. Read `.awm/artifacts.md` for available data from sibling scopes\n"
        f"4. Search for relevant skill protocols: `skills_search query=\"your task description\"`\n\n"
        f"## Work\n\n"
        f"- Code is in the current directory (this IS the git worktree)\n"
        f"- Project data is at `.awm/data/`\n"
        f"- Skill protocols are at `.awm/skills/`\n"
        f"- Do NOT edit `.awm/history.md` or `.awm/artifacts.md` — use MCP tools (see prefaces in those files)\n\n"
        f"## Debrief\n\n"
        f"When the user asks you to debrief (or says \"debrief\"), follow the debrief skill:\n"
        f"{debrief_hint}\n"
    )


def _generate_history_md(project: str, scope: str) -> str:
    """Generate history.md content from session logs for a project."""
    from awm.services.sessions import _display_title

    preface = (
        f"<!-- AUTO-GENERATED by AWM. Do NOT edit this file directly.\n"
        f"     To refresh: `awm_refresh project={project} scope={scope}`\n"
        f"     To add lessons: `session_log` with decisions/issues/next-steps (see debrief skill)\n"
        f"     To search: `session_search project={project} scope={scope}` or `session_list project={project}` -->\n\n"
        f"# Project History: {project}\n\n"
    )

    conn = get_connection()
    try:
        # Sibling scopes
        siblings = conn.execute(
            "SELECT scope, session FROM scopes WHERE project=? AND scope!=? AND status='active'",
            (project, scope),
        ).fetchall()

        # Open sessions (unresolved). Alias legacy_id → id so the markdown
        # formatter doesn't need to know about the v32 column rename.
        open_sessions = conn.execute(
            "SELECT legacy_id AS id, title, summary, scope, skill_path, "
            "       outcome, deviations, suggestions "
            "FROM session_logs WHERE project=? AND resolved_at IS NULL "
            "ORDER BY logged_at DESC LIMIT 50",
            (project,),
        ).fetchall()

        # Resolved sessions
        resolved_sessions = conn.execute(
            "SELECT legacy_id AS id, title, summary FROM session_logs "
            "WHERE project=? AND resolved_at IS NOT NULL "
            "ORDER BY resolved_at DESC LIMIT 50",
            (project,),
        ).fetchall()
    finally:
        conn.close()

    sections = []

    # Sibling scopes
    if siblings:
        lines = ["## Active Sibling Scopes\n"]
        for s in siblings:
            lines.append(f"- **{s['scope']}** (session {s['session']})")
        sections.append("\n".join(lines))

    # Open sessions — full details
    if open_sessions:
        by_skill: dict[str, list] = {}
        for s in open_sessions:
            key = s["skill_path"] or "(freeform)"
            by_skill.setdefault(key, []).append(s)

        lines = ["## Open\n"]
        for skill_key, entries in by_skill.items():
            lines.append(f"### Skill: {skill_key}\n")
            for s in entries[:5]:
                title = _display_title(s)
                outcome = f" [{s['outcome']}]" if s["outcome"] else ""
                scope_tag = f" ({s['scope']})" if s["scope"] != scope else ""
                lines.append(f"**[#{s['id']}] {title}**{outcome}{scope_tag}")
                if s["deviations"]:
                    lines.append(f"- Deviations: {s['deviations']}")
                if s["suggestions"]:
                    lines.append(f"- Suggestions: {s['suggestions']}")
                lines.append("")
        sections.append("\n".join(lines))

    # Resolved sessions — compact one-liners
    if resolved_sessions:
        lines = ["## Resolved\n"]
        for s in resolved_sessions:
            title = _display_title(s)
            lines.append(f"- [#{s['id']}] {title}")
        sections.append("\n".join(lines))

    if not sections:
        sections.append("*No session entries yet. Sessions will appear here after agents log them via `session_log`.*\n")

    return preface + "\n".join(sections)


def _generate_artifacts_md(project: str, scope: str) -> str:
    """Generate artifacts.md content from the artifact registry for a project."""
    preface = (
        f"<!-- AUTO-GENERATED by AWM. Do NOT edit this file directly.\n"
        f"     To refresh: `awm_refresh project={project} scope={scope}`\n"
        f"     To register outputs: `artifact_register project={project} scope={scope} name=\"...\" path=\"...\" artifact_type=...`\n"
        f"     To search: `artifact_search project={project} query=\"...\"` -->\n\n"
        f"# Project Artifacts: {project}\n\n"
    )

    conn = get_connection()
    try:
        artifacts = conn.execute(
            "SELECT * FROM artifacts WHERE project=? AND status='current' ORDER BY artifact_type, name",
            (project,),
        ).fetchall()
    finally:
        conn.close()

    if not artifacts:
        return preface + "*No artifacts registered yet. Use `artifact_register` to add outputs.*\n"

    # Group by type
    by_type: dict[str, list] = {}
    for a in artifacts:
        by_type.setdefault(a["artifact_type"], []).append(a)

    sections = []
    for atype, items in by_type.items():
        lines = [f"## {atype.title()}s\n"]
        lines.append("| Name | Path | Format | Scope | Description |")
        lines.append("|------|------|--------|-------|-------------|")
        for a in items:
            desc = (a["description"] or "")[:60]
            fmt = a["format"] or ""
            lines.append(f"| {a['name']} | `{a['path']}` | {fmt} | {a['scope']} | {desc} |")
        sections.append("\n".join(lines))

    return preface + "\n\n".join(sections) + "\n"


def refresh_history(project: str, scope: str) -> str:
    """Regenerate .awm/history.md for a scope. Returns the content written."""
    validate_name(project, kind="project name")
    validate_name(scope, kind="scope name")
    repo_dir = PROJECTS_DIR / project / scope
    awm_dir = _get_awm_dir(repo_dir)
    content = _generate_history_md(project, scope)
    awm_dir.mkdir(parents=True, exist_ok=True)
    (awm_dir / "history.md").write_text(content)
    # Clean up stale knowledge.md from before the rename
    (awm_dir / "knowledge.md").unlink(missing_ok=True)
    return content


def refresh_artifacts(project: str, scope: str) -> str:
    """Regenerate .awm/artifacts.md for a scope. Returns the content written."""
    validate_name(project, kind="project name")
    validate_name(scope, kind="scope name")
    repo_dir = PROJECTS_DIR / project / scope
    awm_dir = _get_awm_dir(repo_dir)
    content = _generate_artifacts_md(project, scope)
    awm_dir.mkdir(parents=True, exist_ok=True)
    (awm_dir / "artifacts.md").write_text(content)
    return content


def awm_refresh(project: str, scope: str) -> dict:
    """Refresh both history.md and artifacts.md for a scope."""
    validate_name(project, kind="project name")
    validate_name(scope, kind="scope name")
    h = refresh_history(project, scope)
    a = refresh_artifacts(project, scope)
    return {
        "message": f"Refreshed .awm/ for {project}/{scope}",
        "history_lines": len(h.splitlines()),
        "artifacts_lines": len(a.splitlines()),
    }


def ensure_vagrant_repo() -> Path:
    """Bootstrap the unified vagrant-scopes bare repo + matching data dirs.

    Idempotent: safe to run on every peer that wants to host vagrant scopes.
    Mirrors the fresh-repo path in :func:`awm.services.projects.create_project`
    but creates the bare repo under the reserved ``_vagrant`` project name and
    points ``origin`` at the runtime-configurable
    ``vagrant_scopes_repo_url`` (default ``git@github.com:{GITHUB_USER}/vagrant-scopes.git``).

    Returns the bare repo Path.
    """
    from awm.services.config_service import get_vagrant_scopes_repo_url

    bare_dir = PROJECTS_DIR / VAGRANT_PROJECT / ".bare"
    project_dir = bare_dir.parent
    project_dir.mkdir(parents=True, exist_ok=True)

    bare_exists = bare_dir.exists()
    if not bare_exists:
        r = run_git(["git", "init", "--bare", str(bare_dir)])
        if r.returncode != 0:
            raise RuntimeError(f"git init --bare failed: {r.stderr}")

    repo_url = get_vagrant_scopes_repo_url()

    # Create the GitHub repo if `gh` is available and it doesn't exist yet.
    # Tolerate "already exists" errors — the remote may have been pre-created
    # or a previous bootstrap may have made it.
    if shutil.which("gh"):
        # `gh repo view {GITHUB_USER}/vagrant-scopes` is cheaper than `create`
        # for the common case where the repo already exists.
        repo_slug = f"{GITHUB_USER}/vagrant-scopes"
        view = run_git(["gh", "repo", "view", repo_slug])
        if view.returncode != 0:
            create = run_git(["gh", "repo", "create", repo_slug, "--private"])
            # Tolerate the "already exists" failure mode; surface anything else.
            if create.returncode != 0 and "already exists" not in (create.stderr or ""):
                raise RuntimeError(f"gh repo create failed: {create.stderr}")

    # Ensure origin remote is set / matches the configured URL.
    existing = run_git(["git", "-C", str(bare_dir), "remote", "get-url", "origin"])
    if existing.returncode != 0:
        run_git(["git", "-C", str(bare_dir), "remote", "add", "origin", repo_url])
    elif (existing.stdout or "").strip() != repo_url:
        run_git(["git", "-C", str(bare_dir), "remote", "set-url", "origin", repo_url])

    # If the bare repo is brand-new (no refs), seed an empty `main` and push.
    has_main = run_git(["git", "-C", str(bare_dir), "rev-parse", "--verify",
                        "refs/heads/main"])
    if has_main.returncode != 0:
        with tempfile.TemporaryDirectory() as tmp:
            init_dir = Path(tmp) / "init"
            run_git(["git", "clone", str(bare_dir), str(init_dir)])
            run_git(["git", "-C", str(init_dir), "checkout", "-b", "main"])
            run_git(["git", "-C", str(init_dir), "commit", "--allow-empty",
                     "-m", "Initial commit for vagrant-scopes"])
            # Push to the local bare; pushing to GitHub is best-effort so a
            # missing network or auth doesn't block local provisioning.
            run_git(["git", "-C", str(init_dir), "push", "origin", "main"])
            if shutil.which("gh"):
                run_git(["git", "-C", str(bare_dir), "push", "origin", "main"])

    # `git init --bare` may leave HEAD pointing at refs/heads/master (depending
    # on git's init.defaultBranch). Make sure HEAD tracks main so callers like
    # detect_default_branch resolve correctly.
    run_git(["git", "-C", str(bare_dir), "symbolic-ref", "HEAD",
             "refs/heads/main"])

    # Ensure data dirs exist so the data symlink in each vagrant worktree
    # has a valid target.
    for d in [
        DATA_DIR / VAGRANT_PROJECT / "raw",
        DATA_DIR / VAGRANT_PROJECT / "staged",
    ]:
        d.mkdir(parents=True, exist_ok=True)

    return bare_dir


def _vagrant_scope_name(user_as: str) -> str:
    """Slugify a ``user_as`` identifier into a valid vagrant scope name."""
    import re
    safe = re.sub(r"[^A-Za-z0-9_-]", "-", user_as).strip("-")
    return f"user-{safe}" if safe else "user-anon"


def vagrant_scope_identifier(user_as: str) -> str:
    """Return the ``project/scope`` identifier for ``user_as``'s vagrant scope.

    Matches the ``scope`` field shape returned by ``GET /rooms/{id}/agents``,
    so the web UI can identify which agent in a room is "the manager".
    """
    return f"{VAGRANT_PROJECT}/{_vagrant_scope_name(user_as)}"


def ensure_vagrant_session(user_as: str) -> tuple[str, str]:
    """Ensure a vagrant scope and default room exist for ``user_as``.

    Idempotent. The scope name is derived from ``user_as`` so each
    authenticated user lands in their own room (e.g. ``user:operator``
    → scope ``user-user-operator`` under project ``_vagrant``). The
    room id is pinned in the ``config`` table under
    ``vagrant_session_room:<scope_name>`` so re-connects find the same
    room; if the pinned room is gone or closed, a fresh one is created.

    Returns ``(scope_uuid, room_id)``.
    """
    from awm.services.config_service import get_config, set_config
    from awm.services import rooms as rooms_svc

    scope_name = _vagrant_scope_name(user_as)
    bare_dir = PROJECTS_DIR / VAGRANT_PROJECT / ".bare"
    if not bare_dir.exists():
        raise FileNotFoundError(
            f"Vagrant-scopes repo not initialized at {bare_dir}. "
            f"Run `awm vagrant-init` first."
        )

    # 1. Ensure scope row + worktree.
    conn = get_connection()
    try:
        row = conn.execute(
            "SELECT uuid FROM scopes WHERE project=? AND scope=? AND status='active'",
            (VAGRANT_PROJECT, scope_name),
        ).fetchone()
    finally:
        conn.close()
    if row is None:
        create_scope(ScopeCreateRequest(project=VAGRANT_PROJECT, scope=scope_name))
        conn = get_connection()
        try:
            row = conn.execute(
                "SELECT uuid FROM scopes WHERE project=? AND scope=? AND status='active'",
                (VAGRANT_PROJECT, scope_name),
            ).fetchone()
        finally:
            conn.close()
    scope_uuid = row["uuid"]

    # 2. Ensure default room. Track binding in the config table so re-connects
    #    find the same room without scanning.
    pointer_key = f"vagrant_session_room:{scope_name}"
    room_id = get_config(pointer_key)
    if room_id:
        existing = rooms_svc.get_room(room_id)
        if existing is not None and existing.status == "active":
            return scope_uuid, room_id

    scope_identifier = f"{VAGRANT_PROJECT}/{scope_name}"
    room = rooms_svc.create_room(
        topic=f"vagrant session for {user_as}",
        scopes=[scope_identifier],
        opener=user_as,
        close_on_exit=False,
    )
    set_config(pointer_key, room.id)
    return scope_uuid, room.id


_CONTEXT_IMPORT_LINE = "@.awm/context.md"


def _write_scope_opencode_config(awm_dir: Path) -> None:
    """Write ``<awm_dir>/mcp-opencode.json`` for opencode SessionStart wiring.

    Starts from the workspace-level ``<WORKSPACE_ROOT>/.awm/mcp-opencode.json``
    (produced by the OpencodeExporter) if it exists — preserves the full MCP
    catalog — and overlays ``instructions: [".awm/context.md"]`` so opencode
    loads the scope's context.md natively on startup. Idempotent.
    """
    import json
    out: dict
    workspace_cfg = WORKSPACE_ROOT / ".awm" / "mcp-opencode.json"
    if workspace_cfg.is_file():
        try:
            out = json.loads(workspace_cfg.read_text())
        except (OSError, json.JSONDecodeError):
            out = {"$schema": "https://opencode.ai/config.json", "mcp": {}}
    else:
        out = {"$schema": "https://opencode.ai/config.json", "mcp": {}}
    # Relative path — opencode resolves it against cwd (worktree root).
    out["instructions"] = [".awm/context.md"]
    awm_dir.mkdir(parents=True, exist_ok=True)
    (awm_dir / "mcp-opencode.json").write_text(json.dumps(out, indent=2) + "\n")


def _is_tracked(worktree_dir: Path, path: str) -> bool:
    """True if ``path`` is tracked by git in ``worktree_dir``."""
    res = subprocess.run(
        ["git", "-C", str(worktree_dir), "ls-files", "--error-unmatch", path],
        capture_output=True,
    )
    return res.returncode == 0


def _strip_context_import(text: str) -> tuple[str, bool]:
    """Remove a trailing ``@.awm/context.md`` line from ``text``.

    Returns ``(new_text, changed)``. Trims one trailing blank line left
    behind by the removal so the file ends with a single newline.
    """
    lines = text.splitlines(keepends=True)
    changed = False
    while lines and lines[-1].strip() == _CONTEXT_IMPORT_LINE:
        lines.pop()
        changed = True
        # Eat at most one orphan blank line left behind.
        if lines and lines[-1].strip() == "":
            lines.pop()
    if not changed:
        return text, False
    new = "".join(lines)
    if new and not new.endswith("\n"):
        new += "\n"
    return new, True


def _heal_worktree(worktree_dir: Path, *, project: str, scope: str, dry_run: bool) -> dict:
    """Bring a single worktree to the canonical tier-3 state.

    Tier-3 must only contain ``.awm/``. This function:

    1. Strips any trailing ``@.awm/context.md`` import line from a
       tracked ``AGENTS.md`` (the leak that #216 cleaned up across 37
       worktrees; the recurrence vector is closed here).
    2. Deletes ``AGENTS.md`` if untracked (template-created scope-local
       chrome from the old harness-context wiring).
    3. Deletes ``CLAUDE.md`` if it is a symlink to ``AGENTS.md`` or is
       otherwise untracked.
    4. Generates ``.awm/context.md`` via ``_default_context`` if missing.

    ``dry_run=True`` reports what would happen without mutating files.
    """
    actions: dict[str, str | None] = {
        "import_line": None, "agents_md": None,
        "claude_md": None, "context_md": None,
    }

    agents_path = worktree_dir / "AGENTS.md"
    if agents_path.is_file() and not agents_path.is_symlink():
        if _is_tracked(worktree_dir, "AGENTS.md"):
            body = agents_path.read_text()
            new_body, changed = _strip_context_import(body)
            if changed:
                actions["import_line"] = "stripped"
                if not dry_run:
                    agents_path.write_text(new_body)
        else:
            actions["agents_md"] = "deleted:untracked"
            if not dry_run:
                agents_path.unlink()

    claude_path = worktree_dir / "CLAUDE.md"
    if claude_path.is_symlink():
        try:
            target = os.readlink(str(claude_path))
        except OSError:
            target = ""
        if target == "AGENTS.md":
            actions["claude_md"] = "deleted:symlink"
            if not dry_run:
                claude_path.unlink()
        elif not _is_tracked(worktree_dir, "CLAUDE.md"):
            actions["claude_md"] = "deleted:untracked-symlink"
            if not dry_run:
                claude_path.unlink()
    elif claude_path.exists():
        if not _is_tracked(worktree_dir, "CLAUDE.md"):
            actions["claude_md"] = "deleted:untracked"
            if not dry_run:
                claude_path.unlink()

    awm_dir = worktree_dir / ".awm"
    context_path = awm_dir / "context.md"
    if not context_path.exists():
        actions["context_md"] = "created"
        if not dry_run:
            awm_dir.mkdir(parents=True, exist_ok=True)
            context_path.write_text(_default_context(project, scope))

    return actions


def heal_scopes(project: str | None = None, dry_run: bool = False) -> list[dict]:
    """Cleanup pass: enforce tier-3 = ``.awm/`` only across active scopes.

    For each active scope worktree: strip any leaked ``@.awm/context.md``
    line from a tracked ``AGENTS.md``, remove untracked scope-level
    ``AGENTS.md`` / ``CLAUDE.md`` / ``CLAUDE.md→AGENTS.md`` symlink,
    and back-fill ``.awm/context.md`` if missing. Idempotent.

    With ``dry_run=True`` the report shows intended actions without
    mutating files — use this before bulk runs to sanity-check.
    """
    conn = get_connection()
    try:
        sql = "SELECT project, scope, worktree FROM scopes WHERE status='active'"
        params: list = []
        if project:
            sql += " AND project=?"
            params.append(project)
        rows = conn.execute(sql, params).fetchall()
    finally:
        conn.close()

    report: list[dict] = []
    for row in rows:
        worktree = Path(row["worktree"])
        if not worktree.exists():
            report.append({
                "project": row["project"], "scope": row["scope"],
                "worktree": str(worktree), "ok": False,
                "error": "worktree missing",
            })
            continue
        try:
            actions = _heal_worktree(
                worktree, project=row["project"], scope=row["scope"],
                dry_run=dry_run,
            )
            report.append({
                "project": row["project"], "scope": row["scope"],
                "worktree": str(worktree), "ok": True,
                "dry_run": dry_run, "actions": actions,
            })
        except OSError as exc:
            report.append({
                "project": row["project"], "scope": row["scope"],
                "worktree": str(worktree), "ok": False,
                "error": f"{type(exc).__name__}: {exc}",
            })
    return report


def create_scope(req: ScopeCreateRequest) -> ScopeActionResponse:
    """Create a new scope: git worktree + .awm/ metadata directory."""
    validate_name(req.project, kind="project name")
    validate_name(req.scope, kind="scope name")
    bare_dir = PROJECTS_DIR / req.project / ".bare"
    if not bare_dir.exists():
        if req.project == VAGRANT_PROJECT:
            raise FileNotFoundError(
                f"Vagrant-scopes repo not initialized at {bare_dir}. "
                f"Run `awm vagrant-init` first."
            )
        raise FileNotFoundError(f"Project '{req.project}' not found (expected {bare_dir})")

    from_branch = req.from_branch or detect_default_branch(bare_dir)
    repo_dir = PROJECTS_DIR / req.project / req.scope
    feature_branch = f"feat/{req.scope}"

    # Check for existing sessions
    conn = get_connection()
    try:
        row = conn.execute(
            "SELECT MAX(session) as max_session FROM scopes WHERE project=? AND scope=?",
            (req.project, req.scope),
        ).fetchone()
        session_num = (row["max_session"] or 0) + 1 if row and row["max_session"] else 1

        active = conn.execute(
            "SELECT uuid FROM scopes WHERE project=? AND scope=? AND status='active'",
            (req.project, req.scope),
        ).fetchone()
        if active:
            raise FileExistsError(
                f"Scope '{req.scope}' already has an active session in project '{req.project}'"
            )
    finally:
        conn.close()

    # Clean up old worktree if it exists from a previous session
    if repo_dir.exists():
        _cleanup_worktree(bare_dir, repo_dir, feature_branch)

    # 1. Create git worktree at projects/{project}/{scope}/
    r = run_git(["git", "-C", str(bare_dir), "worktree", "add",
              f"../{req.scope}", "-b", feature_branch, from_branch])
    if r.returncode != 0:
        raise RuntimeError(f"Failed to create worktree: {r.stderr}")

    # 2. Create .awm/ metadata directory inside the worktree
    awm_dir = _get_awm_dir(repo_dir)
    awm_dir.mkdir(parents=True, exist_ok=True)

    # 3. Create symlinks: data, skills
    data_link = awm_dir / "data"
    if data_link.is_symlink() or data_link.exists():
        data_link.unlink()
    data_target = DATA_DIR / req.project
    data_target.mkdir(parents=True, exist_ok=True)
    data_link.symlink_to(data_target)

    skills_link = awm_dir / "skills"
    if skills_link.is_symlink() or skills_link.exists():
        skills_link.unlink()
    skills_link.symlink_to(SKILLS_DIR)

    # 4. Write context.md
    context_content = req.context or _default_context(req.project, req.scope)
    (awm_dir / "context.md").write_text(context_content)

    # 5. Generate history.md and artifacts.md
    (awm_dir / "history.md").write_text(_generate_history_md(req.project, req.scope))
    (awm_dir / "artifacts.md").write_text(_generate_artifacts_md(req.project, req.scope))

    # 6. Per-scope opencode config — pulls in .awm/context.md via
    # `instructions` so opencode loads scope orientation natively without
    # any tier-3 file at the worktree root. Claude Code gets the same
    # bytes via the SessionStart hook (awm context emit).
    _write_scope_opencode_config(awm_dir)

    # 7. Record in DB
    now = _now_iso()
    conn = get_connection()
    try:
        origin = _local_peer_id()
        legacy = next_legacy_id(conn, "scopes", origin)
        conn.execute(
            "INSERT INTO scopes "
            "(uuid, legacy_id, origin_peer, project, scope, status, branch, "
            " worktree, repo_path, session, created_at, updated_at) "
            "VALUES (?, ?, ?, ?, ?, 'active', ?, ?, ?, ?, ?, ?)",
            (new_uuid(), legacy, origin, req.project, req.scope,
             feature_branch, str(repo_dir), str(repo_dir), session_num,
             now, now),
        )
        conn.commit()
    finally:
        conn.close()

    return ScopeActionResponse(
        project=req.project,
        scope=req.scope,
        status="active",
        session=session_num,
        message=f"Created scope at projects/{req.project}/{req.scope} (.awm/ initialized) on branch {feature_branch}, session {session_num}",
    )


def update_scope(project: str, scope: str, req: ScopeUpdateRequest) -> ScopeActionResponse:
    """Complete a scope."""
    validate_name(project, kind="project name")
    validate_name(scope, kind="scope name")
    bare_dir = PROJECTS_DIR / project / ".bare"
    repo_dir = PROJECTS_DIR / project / scope

    if not bare_dir.exists():
        raise FileNotFoundError(f"Bare repository not found at {bare_dir}")

    feature_branch = f"feat/{scope}"
    now = _now_iso()

    if req.action != "complete":
        raise ValueError(f"Unknown action: {req.action}. Only 'complete' is supported.")

    conn = get_connection()
    try:
        conn.execute(
            "UPDATE scopes SET status='completed', updated_at=? WHERE project=? AND scope=? AND status='active'",
            (now, project, scope),
        )
        conn.commit()
    finally:
        conn.close()

    merge_msg = ""
    if req.merge:
        default_branch = detect_default_branch(bare_dir)
        main_worktree = PROJECTS_DIR / project / default_branch
        if not main_worktree.exists():
            raise FileNotFoundError(f"Main worktree not found at {main_worktree}")
        run_git(["git", "-C", str(main_worktree), "checkout", default_branch])
        r = run_git(["git", "-C", str(main_worktree), "merge", feature_branch,
                  "-m", f"Merge {feature_branch} into {default_branch}"])
        if r.returncode != 0:
            raise RuntimeError(f"Merge failed: {r.stderr}")
        run_git(["git", "-C", str(main_worktree), "push"])
        merge_msg = f", merged into {default_branch}"

    if req.cleanup:
        _cleanup_worktree(bare_dir, repo_dir, feature_branch)

    return ScopeActionResponse(
        project=project, scope=scope, status="completed",
        message=f"Scope completed{merge_msg}",
    )


def sync_scope(project: str, scope: str, req: ScopeSyncRequest) -> ScopeActionResponse:
    """Bring a scope's feature branch up to date with its base branch.

    Merges (default) or rebases the base branch into feat/{scope} inside the
    scope's existing worktree. Refuses if the worktree is dirty. Does not fetch
    — caller pulls the base branch first if upstream commits are wanted.
    """
    validate_name(project, kind="project name")
    validate_name(scope, kind="scope name")
    bare_dir = PROJECTS_DIR / project / ".bare"
    repo_dir = PROJECTS_DIR / project / scope
    feature_branch = f"feat/{scope}"

    if not bare_dir.exists():
        raise FileNotFoundError(f"Bare repository not found at {bare_dir}")
    if not repo_dir.exists():
        raise FileNotFoundError(f"Worktree not found at {repo_dir}")

    base = req.from_branch or detect_default_branch(bare_dir)

    conn = get_connection()
    try:
        row = conn.execute(
            "SELECT uuid FROM scopes WHERE project=? AND scope=? AND status='active'",
            (project, scope),
        ).fetchone()
    finally:
        conn.close()
    if row is None:
        raise FileNotFoundError(f"No active scope '{scope}' found in project '{project}'")

    # Dirty-tree gate
    r = run_git(["git", "-C", str(repo_dir), "status", "--porcelain"])
    if r.returncode != 0:
        raise RuntimeError(f"git status failed: {r.stderr}")
    if r.stdout.strip():
        raise RuntimeError(
            f"Worktree has uncommitted changes — refusing to sync:\n{r.stdout}"
        )

    # Confirm HEAD is on feature_branch
    r = run_git(["git", "-C", str(repo_dir), "rev-parse", "--abbrev-ref", "HEAD"])
    if r.returncode != 0:
        raise RuntimeError(f"git rev-parse failed: {r.stderr}")
    current = r.stdout.strip()
    if current != feature_branch:
        raise RuntimeError(
            f"Worktree HEAD is on '{current}', expected '{feature_branch}'. "
            f"Check out the feature branch before syncing."
        )

    # Run the sync
    if req.strategy == "merge":
        r = run_git([
            "git", "-C", str(repo_dir), "merge", base,
            "-m", f"Sync {base} into {feature_branch}",
        ])
    else:  # rebase
        r = run_git(["git", "-C", str(repo_dir), "rebase", base])

    if r.returncode != 0:
        raise RuntimeError(
            f"{req.strategy} failed: {r.stderr or r.stdout}\n"
            f"Worktree left mid-{req.strategy}; resolve and re-run, "
            f"or `git {req.strategy} --abort` to undo."
        )

    now = _now_iso()
    conn = get_connection()
    try:
        conn.execute(
            "UPDATE scopes SET updated_at=? WHERE project=? AND scope=? AND status='active'",
            (now, project, scope),
        )
        conn.commit()
    finally:
        conn.close()

    return ScopeActionResponse(
        project=project,
        scope=scope,
        status="active",
        message=f"Synced {feature_branch} with {base} via {req.strategy}",
    )


def delete_scope(project: str, scope: str) -> ScopeActionResponse:
    """Delete a scope — clean up worktree, branch, and mark as deleted in DB."""
    validate_name(project, kind="project name")
    validate_name(scope, kind="scope name")
    bare_dir = PROJECTS_DIR / project / ".bare"
    repo_dir = PROJECTS_DIR / project / scope
    feature_branch = f"feat/{scope}"

    if not bare_dir.exists():
        raise FileNotFoundError(f"Bare repository not found at {bare_dir}")

    conn = get_connection()
    try:
        row = conn.execute(
            "SELECT uuid, status FROM scopes "
            "WHERE project=? AND scope=? AND status IN ('active', 'completed') "
            "ORDER BY updated_at DESC LIMIT 1",
            (project, scope),
        ).fetchone()
        if row is None:
            raise FileNotFoundError(f"No active or completed scope '{scope}' found in project '{project}'")

        _cleanup_worktree(bare_dir, repo_dir, feature_branch)

        now = _now_iso()
        conn.execute(
            "UPDATE scopes SET status='deleted', updated_at=? WHERE uuid=?",
            (now, row["uuid"]),
        )
        conn.commit()
    finally:
        conn.close()

    return ScopeActionResponse(
        project=project, scope=scope, status="deleted",
        message=f"Scope deleted, worktree and branch cleaned up",
    )


def list_scopes(status: str | None = None, project: str | None = None) -> ScopeListResponse:
    """List scopes, optionally filtered by status and/or project."""
    conn = get_connection()
    try:
        query = "SELECT project, scope, status, branch, worktree, repo_path, session FROM scopes WHERE 1=1"
        params: list[str] = []
        if status and status != "all":
            query += " AND status = ?"
            params.append(status)
        if project:
            query += " AND project = ?"
            params.append(project)
        query += " ORDER BY project, scope"
        rows = conn.execute(query, params).fetchall()
    finally:
        conn.close()

    scopes = [
        ScopeInfo(
            project=r["project"], scope=r["scope"], status=r["status"],
            branch=r["branch"], worktree=r["worktree"],
            repo_path=r["repo_path"], session=r["session"],
        )
        for r in rows
    ]
    return ScopeListResponse(scopes=scopes, total=len(scopes))


