"""Scope CRUD — create, complete, delete, list, refresh."""

from __future__ import annotations

import shutil
import subprocess
from datetime import datetime, timezone
from pathlib import Path

from awm.config import (
    WORKSPACE_ROOT,
    PROJECTS_DIR,
    DATA_DIR,
    SKILLS_DIR,
)
from awm.db import get_connection
from awm.git_utils import run_git, detect_default_branch
from awm.models import (
    ScopeCreateRequest,
    ScopeUpdateRequest,
    ScopeInfo,
    ScopeListResponse,
    ScopeActionResponse,
)


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def _get_awm_dir(repo_dir: Path) -> Path:
    """Return the .awm/ metadata directory inside a scope worktree."""
    return repo_dir / ".awm"


def _cleanup_worktree(bare_dir: Path, worktree_dir: Path, feature_branch: str) -> None:
    """Remove a scope's worktree and branch, ignoring errors."""
    r = run_git(["git", "-C", str(bare_dir), "worktree", "remove", str(worktree_dir), "--force"])
    if r.returncode != 0 and worktree_dir.exists():
        shutil.rmtree(worktree_dir, ignore_errors=True)
    # Only remove the target's metadata dir. NEVER run a blanket
    # `git worktree prune` here: under the .bare layout git sometimes flags
    # healthy sibling worktrees as prunable due to path-resolution quirks, and
    # a blanket prune will wipe their `.bare/worktrees/<name>/` metadata too,
    # leaving dangling `.git` gitlinks in their working directories. See
    # inbox #111 (2026-04-05).
    meta_dir = bare_dir / "worktrees" / worktree_dir.name
    if meta_dir.exists():
        shutil.rmtree(meta_dir, ignore_errors=True)
    run_git(["git", "-C", str(bare_dir), "branch", "-D", feature_branch])


def _default_context(project: str, scope: str) -> str:
    """Generate the default context.md content for a new scope."""
    # Resolve the debrief skill by frontmatter name, not hardcoded path, so the
    # generated context.md stays correct if the skill moves.
    from awm.services.skills import find_by_name
    debrief = find_by_name("debrief")
    debrief_hint = (
        f"`skills_get path=\"{debrief.file_path}\"`"
        if debrief
        else "`skills_search query=\"debrief\"`"
    )
    return (
        f"# {project}/{scope}\n\n"
        f"## Startup\n\n"
        f"1. Run `awm_refresh project={project} scope={scope}` to update local history and artifact indexes\n"
        f"2. Read `.awm/history.md` for session history, open issues, and resolved items\n"
        f"3. Read `.awm/artifacts.md` for available data from sibling scopes\n"
        f"4. Search for relevant skill protocols: `skills_search query=\"your task description\"`\n\n"
        f"## Work\n\n"
        f"- Code is in the current directory (this IS the git worktree)\n"
        f"- Project data is at `.awm/data/`\n"
        f"- Skill protocols are at `.awm/skills/`\n"
        f"- Do NOT edit `.awm/history.md` or `.awm/artifacts.md` — use MCP tools (see prefaces in those files)\n\n"
        f"## Debrief\n\n"
        f"When the user asks you to debrief (or says \"debrief\"), follow the debrief skill:\n"
        f"{debrief_hint}\n"
    )


def _generate_history_md(project: str, scope: str) -> str:
    """Generate history.md content from session logs for a project."""
    preface = (
        f"<!-- AUTO-GENERATED by AWM. Do NOT edit this file directly.\n"
        f"     To refresh: `awm_refresh project={project} scope={scope}`\n"
        f"     To add lessons: `session_log` with decisions/issues/next-steps (see debrief skill)\n"
        f"     To search: `session_search project={project}` or `session_list project={project}` -->\n\n"
        f"# Project History: {project}\n\n"
    )

    conn = get_connection()
    try:
        # Sibling scopes
        siblings = conn.execute(
            "SELECT scope, session FROM scopes WHERE project=? AND scope!=? AND status='active'",
            (project, scope),
        ).fetchall()

        # Open sessions (unresolved)
        open_sessions = conn.execute(
            "SELECT * FROM session_logs WHERE project=? AND resolved_at IS NULL ORDER BY logged_at DESC LIMIT 50",
            (project,),
        ).fetchall()

        # Resolved sessions
        resolved_sessions = conn.execute(
            "SELECT id, summary FROM session_logs WHERE project=? AND resolved_at IS NOT NULL ORDER BY resolved_at DESC LIMIT 50",
            (project,),
        ).fetchall()
    finally:
        conn.close()

    sections = []

    # Sibling scopes
    if siblings:
        lines = ["## Active Sibling Scopes\n"]
        for s in siblings:
            lines.append(f"- **{s['scope']}** (session {s['session']})")
        sections.append("\n".join(lines))

    # Open sessions — full details
    if open_sessions:
        by_skill: dict[str, list] = {}
        for s in open_sessions:
            key = s["skill_path"] or "(freeform)"
            by_skill.setdefault(key, []).append(s)

        lines = ["## Open\n"]
        for skill_key, entries in by_skill.items():
            lines.append(f"### Skill: {skill_key}\n")
            for s in entries[:5]:
                outcome = f" [{s['outcome']}]" if s["outcome"] else ""
                lines.append(f"**{s['scope']}**{outcome}: {s['summary']}")
                if s["deviations"]:
                    lines.append(f"- Deviations: {s['deviations']}")
                if s["suggestions"]:
                    lines.append(f"- Suggestions: {s['suggestions']}")
                lines.append("")
        sections.append("\n".join(lines))

    # Resolved sessions — compact one-liners
    if resolved_sessions:
        lines = ["## Resolved\n"]
        for s in resolved_sessions:
            lines.append(f"- [#{s['id']}] {s['summary']}")
        sections.append("\n".join(lines))

    if not sections:
        sections.append("*No session entries yet. Sessions will appear here after agents log them via `session_log`.*\n")

    return preface + "\n".join(sections)


def _generate_artifacts_md(project: str, scope: str) -> str:
    """Generate artifacts.md content from the artifact registry for a project."""
    preface = (
        f"<!-- AUTO-GENERATED by AWM. Do NOT edit this file directly.\n"
        f"     To refresh: `awm_refresh project={project} scope={scope}`\n"
        f"     To register outputs: `artifact_register project={project} scope={scope} name=\"...\" path=\"...\" artifact_type=...`\n"
        f"     To search: `artifact_search project={project} query=\"...\"` -->\n\n"
        f"# Project Artifacts: {project}\n\n"
    )

    conn = get_connection()
    try:
        artifacts = conn.execute(
            "SELECT * FROM artifacts WHERE project=? AND status='current' ORDER BY artifact_type, name",
            (project,),
        ).fetchall()
    finally:
        conn.close()

    if not artifacts:
        return preface + "*No artifacts registered yet. Use `artifact_register` to add outputs.*\n"

    # Group by type
    by_type: dict[str, list] = {}
    for a in artifacts:
        by_type.setdefault(a["artifact_type"], []).append(a)

    sections = []
    for atype, items in by_type.items():
        lines = [f"## {atype.title()}s\n"]
        lines.append("| Name | Path | Format | Scope | Description |")
        lines.append("|------|------|--------|-------|-------------|")
        for a in items:
            desc = (a["description"] or "")[:60]
            fmt = a["format"] or ""
            lines.append(f"| {a['name']} | `{a['path']}` | {fmt} | {a['scope']} | {desc} |")
        sections.append("\n".join(lines))

    return preface + "\n\n".join(sections) + "\n"


def refresh_history(project: str, scope: str) -> str:
    """Regenerate .awm/history.md for a scope. Returns the content written."""
    repo_dir = PROJECTS_DIR / project / scope
    awm_dir = _get_awm_dir(repo_dir)
    content = _generate_history_md(project, scope)
    awm_dir.mkdir(parents=True, exist_ok=True)
    (awm_dir / "history.md").write_text(content)
    # Clean up stale knowledge.md from before the rename
    (awm_dir / "knowledge.md").unlink(missing_ok=True)
    return content


def refresh_artifacts(project: str, scope: str) -> str:
    """Regenerate .awm/artifacts.md for a scope. Returns the content written."""
    repo_dir = PROJECTS_DIR / project / scope
    awm_dir = _get_awm_dir(repo_dir)
    content = _generate_artifacts_md(project, scope)
    awm_dir.mkdir(parents=True, exist_ok=True)
    (awm_dir / "artifacts.md").write_text(content)
    return content


def awm_refresh(project: str, scope: str) -> dict:
    """Refresh both history.md and artifacts.md for a scope."""
    h = refresh_history(project, scope)
    a = refresh_artifacts(project, scope)
    return {
        "message": f"Refreshed .awm/ for {project}/{scope}",
        "history_lines": len(h.splitlines()),
        "artifacts_lines": len(a.splitlines()),
    }


def create_scope(req: ScopeCreateRequest) -> ScopeActionResponse:
    """Create a new scope: git worktree + .awm/ metadata directory."""
    bare_dir = PROJECTS_DIR / req.project / ".bare"
    if not bare_dir.exists():
        raise FileNotFoundError(f"Project '{req.project}' not found (expected {bare_dir})")

    from_branch = req.from_branch or detect_default_branch(bare_dir)
    repo_dir = PROJECTS_DIR / req.project / req.scope
    feature_branch = f"feat/{req.scope}"

    # Check for existing sessions
    conn = get_connection()
    try:
        row = conn.execute(
            "SELECT MAX(session) as max_session FROM scopes WHERE project=? AND scope=?",
            (req.project, req.scope),
        ).fetchone()
        session_num = (row["max_session"] or 0) + 1 if row and row["max_session"] else 1

        active = conn.execute(
            "SELECT id FROM scopes WHERE project=? AND scope=? AND status='active'",
            (req.project, req.scope),
        ).fetchone()
        if active:
            raise FileExistsError(
                f"Scope '{req.scope}' already has an active session in project '{req.project}'"
            )
    finally:
        conn.close()

    # Clean up old worktree if it exists from a previous session
    if repo_dir.exists():
        _cleanup_worktree(bare_dir, repo_dir, feature_branch)

    # 1. Create git worktree at projects/{project}/{scope}/
    r = run_git(["git", "-C", str(bare_dir), "worktree", "add",
              f"../{req.scope}", "-b", feature_branch, from_branch])
    if r.returncode != 0:
        raise RuntimeError(f"Failed to create worktree: {r.stderr}")

    # 2. Create .awm/ metadata directory inside the worktree
    awm_dir = _get_awm_dir(repo_dir)
    awm_dir.mkdir(parents=True, exist_ok=True)

    # 3. Create symlinks: data, skills
    data_link = awm_dir / "data"
    if data_link.is_symlink() or data_link.exists():
        data_link.unlink()
    data_target = DATA_DIR / req.project
    data_target.mkdir(parents=True, exist_ok=True)
    data_link.symlink_to(data_target)

    skills_link = awm_dir / "skills"
    if skills_link.is_symlink() or skills_link.exists():
        skills_link.unlink()
    skills_link.symlink_to(SKILLS_DIR)

    # 4. Write context.md
    context_content = req.context or _default_context(req.project, req.scope)
    (awm_dir / "context.md").write_text(context_content)

    # 5. Generate history.md and artifacts.md
    (awm_dir / "history.md").write_text(_generate_history_md(req.project, req.scope))
    (awm_dir / "artifacts.md").write_text(_generate_artifacts_md(req.project, req.scope))

    # 6. Record in DB
    now = _now_iso()
    conn = get_connection()
    try:
        conn.execute(
            "INSERT INTO scopes (project, scope, status, branch, worktree, repo_path, session, created_at, updated_at) VALUES (?, ?, 'active', ?, ?, ?, ?, ?, ?)",
            (req.project, req.scope, feature_branch, str(repo_dir), str(repo_dir), session_num, now, now),
        )
        conn.commit()
    finally:
        conn.close()

    return ScopeActionResponse(
        project=req.project,
        scope=req.scope,
        status="active",
        session=session_num,
        message=f"Created scope at projects/{req.project}/{req.scope} (.awm/ initialized) on branch {feature_branch}, session {session_num}",
    )


def update_scope(project: str, scope: str, req: ScopeUpdateRequest) -> ScopeActionResponse:
    """Complete a scope."""
    bare_dir = PROJECTS_DIR / project / ".bare"
    repo_dir = PROJECTS_DIR / project / scope

    if not bare_dir.exists():
        raise FileNotFoundError(f"Bare repository not found at {bare_dir}")

    feature_branch = f"feat/{scope}"
    now = _now_iso()

    if req.action != "complete":
        raise ValueError(f"Unknown action: {req.action}. Only 'complete' is supported.")

    conn = get_connection()
    try:
        conn.execute(
            "UPDATE scopes SET status='completed', updated_at=? WHERE project=? AND scope=? AND status='active'",
            (now, project, scope),
        )
        conn.commit()
    finally:
        conn.close()

    merge_msg = ""
    if req.merge:
        default_branch = detect_default_branch(bare_dir)
        main_worktree = PROJECTS_DIR / project / default_branch
        if not main_worktree.exists():
            raise FileNotFoundError(f"Main worktree not found at {main_worktree}")
        run_git(["git", "-C", str(main_worktree), "checkout", default_branch])
        r = run_git(["git", "-C", str(main_worktree), "merge", feature_branch,
                  "-m", f"Merge {feature_branch} into {default_branch}"])
        if r.returncode != 0:
            raise RuntimeError(f"Merge failed: {r.stderr}")
        run_git(["git", "-C", str(main_worktree), "push"])
        merge_msg = f", merged into {default_branch}"

    if req.cleanup:
        _cleanup_worktree(bare_dir, repo_dir, feature_branch)

    return ScopeActionResponse(
        project=project, scope=scope, status="completed",
        message=f"Scope completed{merge_msg}",
    )


def delete_scope(project: str, scope: str) -> ScopeActionResponse:
    """Delete a scope — clean up worktree, branch, and mark as deleted in DB."""
    bare_dir = PROJECTS_DIR / project / ".bare"
    repo_dir = PROJECTS_DIR / project / scope
    feature_branch = f"feat/{scope}"

    if not bare_dir.exists():
        raise FileNotFoundError(f"Bare repository not found at {bare_dir}")

    conn = get_connection()
    try:
        row = conn.execute(
            "SELECT id, status FROM scopes WHERE project=? AND scope=? AND status IN ('active', 'completed') ORDER BY updated_at DESC LIMIT 1",
            (project, scope),
        ).fetchone()
        if row is None:
            raise FileNotFoundError(f"No active or completed scope '{scope}' found in project '{project}'")

        _cleanup_worktree(bare_dir, repo_dir, feature_branch)

        now = _now_iso()
        conn.execute(
            "UPDATE scopes SET status='deleted', updated_at=? WHERE id=?",
            (now, row["id"]),
        )
        conn.commit()
    finally:
        conn.close()

    return ScopeActionResponse(
        project=project, scope=scope, status="deleted",
        message=f"Scope deleted, worktree and branch cleaned up",
    )


def list_scopes(status: str | None = None, project: str | None = None) -> ScopeListResponse:
    """List scopes, optionally filtered by status and/or project."""
    conn = get_connection()
    try:
        query = "SELECT project, scope, status, branch, worktree, repo_path, session FROM scopes WHERE 1=1"
        params: list[str] = []
        if status and status != "all":
            query += " AND status = ?"
            params.append(status)
        if project:
            query += " AND project = ?"
            params.append(project)
        query += " ORDER BY project, scope"
        rows = conn.execute(query, params).fetchall()
    finally:
        conn.close()

    scopes = [
        ScopeInfo(
            project=r["project"], scope=r["scope"], status=r["status"],
            branch=r["branch"], worktree=r["worktree"],
            repo_path=r["repo_path"], session=r["session"],
        )
        for r in rows
    ]
    return ScopeListResponse(scopes=scopes, total=len(scopes))


