// GENERATED by awm/gateway/awm/gateway/packages/gen.py — do not edit.
// Shared config lives at awm/ui_components/_shared/vite.config.base.ts.
export { default } from '../../ui_components/_shared/vite.config.base';
