#!/usr/bin/env bash
# Canonical install for the awm-dsh service (editable, into the `awm` env), plus
# the node runtime the DeepSeek Harness itself needs.
#
# Three halves, because this service has three kinds of dependency:
#
#   1. Python — the adapter, the supervisor and the mesh front. Installs the
#      component libraries it imports first, then httpsfront (the front is a
#      *configuration* of that component, not a copy of it), then the service.
#
#   2. A node toolchain — its own mamba env pinned to node 24. The harness needs
#      >= 22.19 and the node on the host PATH is older and carries no npm, so
#      borrowing it is not an option.
#
#   3. The harness — installed from the registry rather than built from source:
#      the published frontend package ships its built `dist/`, so the upstream
#      build apparatus buys nothing here. It lands in the service's *state*
#      directory, not the git tree, because a 277 MB node_modules is state.
#
# Every step is idempotent and skips itself when already satisfied, because this
# script runs on every deploy (awm/gateway/install.sh invokes each service's).
#
# Override the target env with AWM_ENV=<name>.
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
WS="$(git -C "$HERE" rev-parse --show-toplevel)"
ENV="${AWM_ENV:-awm}"

# dsh is an explicit developer preview that promises compatibility-breaking
# changes, so the version is pinned and bumping it is a deliberate step.
DSH_VERSION="${DSH_VERSION:-0.1.0-rc.7}"
NODE_ENV_NAME="${DSH_NODE_ENV:-dsh}"
STATE_DIR="${DSH_STATE_DIR:-$WS/.awm/services/dsh}"
RUNTIME_DIR="$STATE_DIR/runtime"

run() { echo "+ pip install -e $*"; mamba run -n "$ENV" pip install -e "$@"; }

run "$WS/awm/service_components/config" --no-deps
run "$WS/awm/service_components/gatewayclient" --no-deps
run "$WS/awm/services/httpsfront" --no-deps
run "$WS/awm/services/dsh"

# Bake the target env's absolute interpreter into a gitignored `.runtime-env`
# sidecar so the hub supervisor can respawn this service under systemd's
# minimal PATH (no `mamba`).
PYBIN="$(mamba run -n "$ENV" python -c 'import sys; print(sys.executable)')"
printf 'AWM_PYTHON=%s\nAWM_ENV_BIN=%s\n' "$PYBIN" "$(dirname "$PYBIN")" \
    > "$HERE/.runtime-env"

# -- the node toolchain -----------------------------------------------------
if mamba run -n "$NODE_ENV_NAME" node --version >/dev/null 2>&1; then
    echo "node env '$NODE_ENV_NAME' present: $(mamba run -n "$NODE_ENV_NAME" node --version)."
else
    echo "Creating node env '$NODE_ENV_NAME' (nodejs 24) …"
    mamba create -y -n "$NODE_ENV_NAME" -c conda-forge 'nodejs>=24,<25'
fi

NODE_BIN="$(dirname "$(mamba run -n "$NODE_ENV_NAME" node -p 'process.execPath')")"
mkdir -p "$STATE_DIR"
# The supervisor respawns under systemd's minimal PATH, where neither `node` nor
# the `mamba` that could find it exists. Recording the absolute directory here
# is what lets it build a working PATH for the child.
printf '%s\n' "$NODE_BIN" > "$STATE_DIR/node-bin"

# -- the harness -----------------------------------------------------------
# pnpm rather than npm: the harness is a pnpm workspace upstream and `dsh plugin`
# shells out to pnpm, but the operative reason is that npm 11's peer resolver
# does not converge on this tree in any usable time. The one npm run that
# finished needed --legacy-peer-deps, which silently omits
# @deepseek-ai/cordis-plugin-group and fails at first launch with
# ERR_MODULE_NOT_FOUND. pnpm resolves the same tree in about ten seconds.
command -v "$NODE_BIN/pnpm" >/dev/null 2>&1 || \
    ( echo "Installing pnpm into env '$NODE_ENV_NAME' …"; \
      PATH="$NODE_BIN:$PATH" "$NODE_BIN/npm" i -g --no-fund --no-audit pnpm )

mkdir -p "$RUNTIME_DIR"
# Both files are generated, so they are rewritten rather than seeded: a hand
# edit here would be silently reverted on the next deploy, and pretending
# otherwise is worse than saying so.
cat > "$RUNTIME_DIR/package.json" <<JSON
{
  "name": "awm-dsh-runtime",
  "private": true,
  "description": "pnpm install target for the DeepSeek Harness the awm dsh service supervises. Generated by awm/services/dsh/install.sh; edits are overwritten.",
  "dependencies": {
    "@deepseek-ai/dsh": "$DSH_VERSION"
  }
}
JSON
cat > "$RUNTIME_DIR/pnpm-workspace.yaml" <<'YAML'
# Generated by awm/services/dsh/install.sh; edits are overwritten.

# The harness resolves plugin packages by bare name from its own boot bundle, so
# pnpm's strict symlinked layout hides them. Hoist to an npm-shaped flat tree.
shamefullyHoist: true
autoInstallPeers: true

# Build scripts pnpm 11 will not run unless the package is named here. All five
# are wanted: node-pty and koffi are the terminal and FFI natives the harness's
# local-subprocess tools need, and dsh-subprocess-local's postinstall is what
# puts its spawn helper in place. Without them the GUI still loads and every
# tool that touches a subprocess fails at use time.
allowBuilds:
  '@deepseek-ai/dsh-subprocess-local': true
  '@google/genai': true
  koffi: true
  node-pty: true
  protobufjs: true
YAML

HAVE=""
if [ -f "$RUNTIME_DIR/node_modules/@deepseek-ai/dsh/package.json" ]; then
    HAVE="$("$NODE_BIN/node" -p \
        "require('$RUNTIME_DIR/node_modules/@deepseek-ai/dsh/package.json').version" \
        2>/dev/null || true)"
fi

if [ "$HAVE" = "$DSH_VERSION" ]; then
    echo "Harness present at $DSH_VERSION."
else
    echo "Installing @deepseek-ai/dsh@$DSH_VERSION into $RUNTIME_DIR …"
    ( cd "$RUNTIME_DIR" && PATH="$NODE_BIN:$PATH" "$NODE_BIN/pnpm" install )
fi

echo "Installed awm-dsh into env '$ENV'."
echo "Runtime:  $RUNTIME_DIR"
echo "DSH_HOME: $STATE_DIR/home"
