//! The invite-code vocabulary.
//!
//! Exactly 1024 words, so a word is ten bits and the arithmetic that turns
//! random bytes into a phrase needs no rejection loop and introduces no bias.
//!
//! The list is filtered rather than merely collected, and `tests` in
//! `invite.rs` re-checks every rule on every build:
//!
//!   - three to eight lowercase ASCII letters, so it is quick to type;
//!   - no two words share their first three letters, which kills the
//!     `bear` / `beard` and `flour` / `flower` class of mishearing;
//!   - no two words are one edit apart, which kills `bat` / `bad`;
//!   - no silent opening (`kn`, `wr`, `gn`, `ps`, `pn`, `rh`) and no word
//!     whose spelling a listener would have to ask about, because this is
//!     read aloud to somebody who then has to type it.
//!
//! Sorted, so `position` can binary-search it.

/// How many bits one word carries. The list length is `1 << WORD_BITS`.
pub const WORD_BITS: u32 = 10;

pub const WORDS: [&str; 1024] = [
    "abacus", "abbey", "abdomen", "ability", "abstract", "accent", "acorn", "acre", "actor",
    "adapter", "adobe", "adult", "advice", "aerial", "affair", "airline", "alarm", "album",
    "alcove", "alfalfa", "alibi", "alley", "almond", "alpaca", "altar", "amber", "ammonia",
    "amulet", "analog", "anchor", "anemone", "angel", "anise", "ankle", "annual", "anthem",
    "anvil", "anxiety", "aperture", "apiary", "apron", "aquarium", "arcade", "arena",
    "argument", "aroma", "arrow", "arsenal", "article", "ashtray", "assembly", "asteroid",
    "athlete", "atlas", "atoll", "attic", "auction", "audience", "august", "aunt", "author",
    "avenue", "aviator", "avocado", "awning", "azalea", "babble", "bacon", "badge", "bagel",
    "ballad", "bamboo", "banjo", "baptism", "basil", "bazaar", "bedrock", "beetle", "beginner",
    "behavior", "bench", "beret", "beverage", "biceps", "bidder", "bingo", "biology", "biplane",
    "birch", "bishop", "blaze", "blemish", "blister", "blossom", "blubber", "bobbin", "boiler",
    "bonsai", "bookcase", "border", "boulder", "bovine", "bowl", "boxcar", "boycott", "breeze",
    "briar", "brook", "brush", "bucket", "buffer", "bugle", "builder", "bullet", "bumper",
    "buoy", "burden", "bushel", "butler", "buyer", "bygone", "cabin", "cackle", "cadet",
    "caffeine", "caiman", "calm", "camel", "cargo", "cashew", "caution", "cavern", "cedar",
    "ceiling", "cello", "census", "cereal", "chalk", "chess", "chili", "choir", "chromium",
    "chunk", "cider", "cigar", "cinema", "cipher", "circle", "cistern", "city", "claw", "clerk",
    "cliff", "cloak", "clumsy", "cobra", "cocoa", "codfish", "coffee", "cognac", "collar",
    "comet", "cone", "cookie", "coping", "cosmic", "cotton", "covenant", "cowboy", "coyote",
    "creek", "crude", "cryptic", "cube", "cuckoo", "cufflink", "cuisine", "culvert", "cupola",
    "curb", "cutter", "cyclone", "cylinder", "cymbal", "cypress", "dagger", "dahlia", "daily",
    "damage", "dancer", "darn", "database", "daughter", "daybreak", "dazzle", "debate", "decal",
    "deduct", "deerskin", "default", "deli", "demand", "denim", "depot", "derby", "detail",
    "device", "dewdrop", "dial", "diet", "dilute", "dime", "diner", "diorama", "dish", "divot",
    "dizzy", "dock", "dodge", "doghouse", "doodle", "dormouse", "dosage", "doubt", "dovetail",
    "doze", "draft", "dreamer", "drill", "droplet", "dryer", "duct", "dude", "duel", "duffel",
    "dulcimer", "dummy", "dungeon", "durable", "dusk", "dynamo", "eagle", "earth", "easel",
    "eatery", "echo", "eclipse", "economy", "eddy", "edible", "effect", "eggplant", "egret",
    "eighth", "elastic", "elder", "elect", "elixir", "eloquent", "elusive", "eminent",
    "emotion", "empire", "emulate", "enable", "ending", "energy", "enforce", "engage",
    "enhance", "enlist", "enormous", "enrich", "ensign", "entail", "enzyme", "episode", "epoxy",
    "equity", "eraser", "errand", "escape", "espresso", "essence", "estate", "ethics",
    "evacuate", "event", "evidence", "evolve", "exceed", "exempt", "exhale", "exit", "expense",
    "eyelet", "fable", "facet", "faith", "falcon", "fang", "farmer", "fasten", "fatal", "fawn",
    "fedora", "feeling", "fellow", "female", "fender", "festival", "fetch", "fiasco", "fiber",
    "fiction", "fiesta", "fifteen", "figure", "filbert", "finch", "fiscal", "fitting",
    "fivefold", "fixture", "fjord", "fleece", "flint", "floppy", "fluke", "flyer", "fodder",
    "foggy", "fondue", "footage", "forage", "founder", "foxglove", "frayed", "frenzy", "friday",
    "frugal", "fudge", "fulcrum", "fumble", "furrow", "futile", "fuzzy", "gadfly", "gaiety",
    "galaxy", "gander", "garage", "gasket", "gather", "gauge", "gazebo", "gearbox", "gecko",
    "geese", "geiger", "gem", "genre", "geode", "geranium", "gesture", "gherkin", "ghost",
    "giant", "giddy", "gift", "gimlet", "ginger", "girl", "gland", "gleam", "glue", "glycerin",
    "goatee", "gobble", "godsend", "gondola", "goose", "gopher", "gospel", "gouda", "grebe",
    "grid", "grove", "gruel", "guava", "gulch", "gumbo", "guppy", "guru", "gusto", "habit",
    "hack", "haddock", "hail", "half", "happy", "hare", "hasty", "haven", "hay", "heckle",
    "hedge", "hefty", "heifer", "helix", "hen", "herb", "hesitate", "hexagon", "heyday",
    "hiccup", "hidden", "highway", "hijack", "hike", "hind", "hippo", "history", "hobby",
    "hockey", "hoist", "hollow", "home", "honey", "hoodie", "hostel", "hound", "hover",
    "hubcap", "huff", "hurry", "husky", "hutch", "hyacinth", "hybrid", "hyena", "hygiene",
    "hymn", "hyphen", "ibex", "icebox", "icing", "icon", "idea", "idiom", "ignite", "illness",
    "image", "imitate", "immune", "inbox", "income", "index", "inept", "infant", "inhale",
    "initial", "inject", "inkling", "inlet", "inner", "inquire", "intact", "invade", "inward",
    "ionic", "iota", "irate", "ironing", "irrigate", "isolate", "issue", "italic", "ivory",
    "ivy", "jade", "jagged", "jalopy", "jamboree", "jangle", "jasmine", "javelin", "jaywalk",
    "jazz", "jealous", "jelly", "jeopardy", "jerk", "jest", "jetty", "jiffy", "jigger", "jilt",
    "jimmy", "jinx", "joint", "jostle", "joust", "joystick", "jubilee", "juggler", "juice",
    "jukebox", "june", "jury", "kabob", "kale", "kangaroo", "kayak", "kazoo", "keel", "kelp",
    "kennel", "kestrel", "kettle", "khaki", "kickoff", "kidney", "kiln", "kimono", "kiosk",
    "kipper", "kismet", "kite", "kiwi", "kohlrabi", "kraken", "kudos", "kumquat", "label",
    "ladle", "lagoon", "lakeside", "lamb", "lard", "launch", "lava", "layer", "lazy", "leash",
    "leek", "leftover", "legacy", "leisure", "lemon", "leopard", "lesson", "letter", "levee",
    "liberty", "lifeboat", "lily", "linen", "lion", "lipstick", "listen", "lizard", "llama",
    "loaf", "loft", "loiter", "lollipop", "lonesome", "loom", "lore", "lounge", "lovebird",
    "lowland", "loyal", "lozenge", "luggage", "lullaby", "lumber", "lung", "lupine", "lute",
    "luxury", "lyceum", "lynx", "lyric", "madrigal", "magma", "mahogany", "maize", "majesty",
    "mammal", "mango", "maple", "march", "mask", "maverick", "maximum", "mayor", "meadow",
    "mechanic", "meerkat", "melon", "member", "menu", "mermaid", "mica", "midway", "migrant",
    "mile", "mimic", "mirage", "misty", "mitten", "moat", "mobile", "model", "mohair",
    "moisture", "moment", "monkey", "moss", "movement", "mower", "mudflat", "muffin", "munch",
    "mural", "music", "mutton", "muzzle", "mystery", "nacho", "namesake", "napkin", "narrate",
    "nautical", "naval", "nearby", "nebula", "nectar", "neighbor", "neon", "nephew", "nerve",
    "neutron", "nibble", "niche", "niece", "ninja", "nitrogen", "nocturne", "nodule", "nomad",
    "nonsense", "north", "notch", "nougat", "novel", "nozzle", "nuance", "nugget", "numeral",
    "nurse", "nutmeg", "nylon", "oakwood", "oar", "oasis", "oatmeal", "obelisk", "oblong",
    "oboe", "observer", "occupy", "ocean", "odyssey", "office", "ogre", "oilcan", "ointment",
    "okra", "olive", "omelet", "omnibus", "onion", "onyx", "opal", "opera", "opossum",
    "optical", "oracle", "orbit", "orchid", "ordeal", "oregano", "oriole", "ornate", "orphan",
    "osprey", "ostrich", "ounce", "outfit", "oven", "oxbow", "oxcart", "oxygen", "oyster",
    "ozone", "pacer", "paddle", "pajamas", "pamphlet", "panda", "papaya", "parka", "pavement",
    "pawpaw", "payload", "peat", "pebble", "penny", "pepper", "permit", "petal", "pewter",
    "pheasant", "phone", "phrase", "physics", "piano", "pier", "pigeon", "pilot", "pine",
    "pioneer", "pitcher", "pixel", "pizza", "plaid", "pliers", "plum", "plywood", "pocket",
    "podium", "poem", "polo", "pomelo", "pond", "poppy", "porch", "powder", "prawn", "premise",
    "prism", "prowl", "pudding", "pueblo", "pulp", "pumice", "pupil", "putty", "pygmy",
    "pyramid", "python", "quack", "quiet", "quota", "rabbit", "raccoon", "radar", "raisin",
    "rake", "rally", "ramp", "ranch", "rascal", "rattle", "rawhide", "rayon", "razor", "rebus",
    "recipe", "redwood", "reed", "refuge", "reindeer", "relay", "remote", "rennet", "repair",
    "retina", "reunion", "revel", "ribbon", "rice", "rifle", "rigging", "rimrock", "ripple",
    "risotto", "rival", "roast", "robin", "rodeo", "rogue", "romaine", "roof", "rope", "rosary",
    "rotor", "rowan", "rubber", "rucksack", "rudder", "ruffle", "ruler", "runner", "rushes",
    "rutabaga", "safari", "salad", "samba", "sandal", "sapling", "sardine", "satin", "sauce",
    "savanna", "sawdust", "scarf", "school", "scissors", "scribe", "seal", "sedan", "segment",
    "seismic", "seltzer", "seminar", "senate", "sermon", "sesame", "settee", "seventh",
    "sewing", "shingle", "shoal", "shrub", "shutter", "sickle", "sifter", "signal", "silk",
    "simmer", "siphon", "sisal", "sitar", "sixth", "sketch", "ski", "slate", "sled", "slicer",
    "slot", "sludge", "smock", "snapper", "sneaker", "snorkel", "soapbox", "sofa", "sojourn",
    "solar", "sombrero", "soprano", "soup", "soybean", "spade", "sphere", "spire", "spoke",
    "sprig", "spyglass", "squid", "staff", "stilt", "stoop", "stratum", "stump", "subway",
    "sugar", "suitcase", "sulfur", "summit", "sundae", "swan", "sweater", "swift", "sycamore",
    "syllable", "syrup", "tabby", "taco", "tadpole", "taffy", "talcum", "tamarind", "tank",
    "tapir", "target", "tatami", "tawny", "taxicab", "teacup", "telegram", "tent", "terrace",
    "textile", "thatch", "theater", "thrush", "thunder", "thyme", "tiara", "tiger", "tinder",
    "tiptoe", "titanium", "toaster", "tobacco", "toga", "token", "tollgate", "tomato", "tongs",
    "topaz", "totem", "toucan", "towel", "toybox", "tremor", "tripod", "trout", "truck", "tuba",
    "tugboat", "tulip", "tumbler", "turban", "tutor", "tweed", "twig", "typhoon", "ukulele",
    "ulster", "unicorn", "upland", "urchin", "usher", "utensil", "vagabond", "valet", "vane",
    "vapor", "varnish", "vector", "velvet", "veneer", "verge", "veteran", "video", "vigil",
    "viking", "villa", "vinyl", "virtue", "visor", "vitamin", "vixen", "vocalist", "volume",
    "voucher", "voyage", "vulture", "waders", "wagon", "waiter", "waltz", "wampum", "wand",
    "wasp", "wax", "wayside", "webbing", "weevil", "wetland", "whale", "wheat", "whiff",
    "wicker", "wigwam", "willow", "window", "wire", "wisdom", "wolf", "wombat", "wonder",
    "wool", "worm", "yawl", "yeast", "yeti", "yew", "yoke", "yucca", "yukon", "zebra", "zenith",
    "zephyr", "zinc", "zircon", "zither", "zodiac",
];
