#!/usr/bin/env bash
# Generate the nginx vhosts that put each person's Trilium on the public web.
#
# One subdomain per person, never one path prefix per person. Trilium has no
# URL-base setting — nothing in its Network config takes one — so an SPA served
# under `/trilium/tony/` requests its own assets from `/` and paints a shell
# that never finishes loading. A subdomain leaves every path where the
# application already expects it.
#
# nginx proxies straight to that person's loopback server, not to the mesh
# front the service raises on other nodes. The public edge here is Cloudflare
# in front of nginx, and the box admits 80 and 443 alone, so a listener in the
# 12501 band would bind a port nothing can reach. Hosts wired this way set
# TRILIUM_FRONTS=0 and raise none.
#
# The gate is Trilium's own login, one per person, one database each. There is
# no awm edge session in front of it on this box — which is the point: the edge
# session is one shared password and could not tell the two people apart.
#
# WARNING: each name needs a DNS record before it resolves. Add an A or CNAME
# for <user>.$DOMAIN pointing at the same place as $DOMAIN, or one wildcard.
# Until then nginx answers on a name nobody can reach.
#
#   trilium-nginx.sh <domain> [outfile]
#
# Ports come from `awm trilium users`, which reads the service's own allocation.
# Do not hand-write them here: the allocation is append-only so that a new user
# never moves an existing one's URL, and a second copy of it would drift.
set -euo pipefail

DOMAIN="${1:?usage: trilium-nginx.sh <domain> [outfile]}"
OUT="${2:-/dev/stdout}"
AWM="${AWM_BIN:-/usr/local/bin/awm}"

USERS_JSON="$("$AWM" trilium users)"

emit() {
    cat <<'HDR'
# Generated by scripts/sirius/trilium-nginx.sh — do not edit.
# One server block per person, each proxying to that person's own Trilium.
HDR
    python3 - "$DOMAIN" "$USERS_JSON" <<'PY'
import json, sys
domain, raw = sys.argv[1], sys.argv[2]
doc = json.loads(raw)
for u in doc.get("users", []):
    print(f"""
server {{
    listen 443 ssl;
    server_name {u['user']}.{domain};

    ssl_certificate     /etc/awm/origin.pem;
    ssl_certificate_key /etc/awm/origin.key;
    ssl_protocols TLSv1.2 TLSv1.3;

    include /etc/nginx/snippets/cloudflare-real-ip.conf;
    server_tokens off;

    # Trilium uploads whole PDFs and imports whole vaults. nginx's 1m default
    # turns either into a 413 the application never sees.
    client_max_body_size 512m;

    location / {{
        proxy_pass http://127.0.0.1:{u['upstream_port']};
        proxy_http_version 1.1;

        # Trilium holds a WebSocket open for every change it renders. Without
        # the upgrade pair the page loads once and then never updates again —
        # which reads as a broken editor, not as a broken proxy.
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        # Trilium marks its session cookie Secure only when it believes the
        # request arrived over HTTPS, and it believes this header. The service
        # sets trustedReverseProxy=loopback, which is what lets it.
        proxy_set_header X-Forwarded-Proto https;

        # An import or an export of a large vault is one long request.
        proxy_read_timeout 600s;
        proxy_send_timeout 600s;
    }}
}}""")
PY
}

emit > "$OUT"
