"""Layout-driven manifest generator.

Walks ``packages/{components,pages}/<name>/`` and writes per-package
``package.json`` (plus, for pages, a one-line ``vite.config.ts``) from
the folder layout + a regex scan of each package's ``src/`` for
``@awm/<x>`` imports.

The generator is idempotent: running it twice in a row produces no diff.
Generated files are committed; CI should diff after a fresh run to catch
forgotten regenerations.

Authors never write ``package.json`` or ``vite.config.ts`` themselves.
The shared Vite config lives at ``packages/_shared/vite.config.base.ts``
(hand-maintained); per-page configs re-export it.
"""

from __future__ import annotations

import json
import logging
import re
from pathlib import Path

log = logging.getLogger("awm.services.packages.gen")


_IMPORT_RE = re.compile(
    r"""from\s+['"](@awm/[a-z0-9_-]+)(?:/[^'"]*)?['"]""",
    re.IGNORECASE,
)
_DYN_IMPORT_RE = re.compile(
    r"""import\(\s*['"](@awm/[a-z0-9_-]+)(?:/[^'"]*)?['"]\s*\)""",
    re.IGNORECASE,
)
_SCAN_EXTS = (".ts", ".tsx", ".js", ".jsx", ".svelte", ".mjs")


def scan_awm_imports(pkg_dir: Path) -> list[str]:
    """Scan src/** of ``pkg_dir`` for ``from '@awm/<x>'`` imports.

    Returns a sorted, de-duplicated list of bare package names
    (``@awm/foo`` not ``@awm/foo/sub``). Self-imports (a package
    importing its own name) are filtered out.
    """
    src = pkg_dir / "src"
    if not src.is_dir():
        return []
    self_name = f"@awm/{pkg_dir.name}"
    found: set[str] = set()
    for path in src.rglob("*"):
        if not path.is_file() or path.suffix not in _SCAN_EXTS:
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        for m in _IMPORT_RE.finditer(text):
            found.add(m.group(1))
        for m in _DYN_IMPORT_RE.finditer(text):
            found.add(m.group(1))
    found.discard(self_name)
    return sorted(found)


def _deps_dict(names: list[str]) -> dict[str, str]:
    # Workspace symlink resolution; "*" satisfies npm's resolver.
    return {n: "*" for n in names}


def gen_component(pkg_dir: Path) -> dict:
    """Return the package.json dict for a packages/components/<name>/.

    Components are pure libraries: ``main``/``exports`` point at source;
    consumers compile via Vite + the Svelte plugin.
    """
    name = pkg_dir.name
    deps = scan_awm_imports(pkg_dir)
    manifest: dict = {
        "name": f"@awm/{name}",
        "version": "0.1.0",
        "private": True,
        "type": "module",
        "main": "./src/index.ts",
        "types": "./src/index.ts",
        "exports": _component_exports(pkg_dir),
        "sideEffects": ["**/*.svelte", "**/*.css"],
    }
    if deps:
        manifest["dependencies"] = _deps_dict(deps)
    return manifest


def _component_exports(pkg_dir: Path) -> dict:
    """Component exports map: ``.`` → src/index.ts, plus one entry per
    top-level src/*.css so consumers can do ``import '@awm/<name>/foo.css'``.
    """
    out: dict = {".": "./src/index.ts"}
    src = pkg_dir / "src"
    if src.is_dir():
        for css in sorted(src.glob("*.css")):
            out[f"./{css.name}"] = f"./src/{css.name}"
    return out


def gen_page(pkg_dir: Path) -> dict:
    """Return the package.json dict for a packages/pages/<name>/.

    Pages are static bundles; the generated manifest carries the build
    script and the inferred ``@awm/*`` dependencies. Per-page
    ``vite.config.ts`` is also (re)written — see ``write_page``.
    """
    name = pkg_dir.name
    deps = scan_awm_imports(pkg_dir)
    manifest: dict = {
        "name": f"@awm/{name}",
        "version": "0.1.0",
        "private": True,
        "type": "module",
        "scripts": {
            "build": "vite build",
        },
    }
    if deps:
        manifest["dependencies"] = _deps_dict(deps)
    return manifest


_PAGE_VITE_CONFIG = (
    "// GENERATED by awm/services/packages/gen.py — do not edit.\n"
    "// Shared config lives at packages/_shared/vite.config.base.ts.\n"
    "export { default } from '../../_shared/vite.config.base';\n"
)


def _write_if_changed(path: Path, text: str) -> bool:
    """Write ``text`` to ``path`` only if its current contents differ.

    Returns True if a write happened. Idempotency is what makes the CI
    gate ``git diff --quiet`` after a fresh run meaningful.
    """
    if path.exists():
        try:
            if path.read_text(encoding="utf-8") == text:
                return False
        except (OSError, UnicodeDecodeError):
            pass
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return True


def _format_manifest(manifest: dict) -> str:
    return json.dumps(manifest, indent=2, sort_keys=False) + "\n"


def write_component(pkg_dir: Path) -> bool:
    pj = pkg_dir / "package.json"
    text = _format_manifest(gen_component(pkg_dir))
    return _write_if_changed(pj, text)


def write_page(pkg_dir: Path) -> bool:
    changed = False
    pj = pkg_dir / "package.json"
    changed |= _write_if_changed(pj, _format_manifest(gen_page(pkg_dir)))
    vc = pkg_dir / "vite.config.ts"
    changed |= _write_if_changed(vc, _PAGE_VITE_CONFIG)
    return changed


def run(repo_root: Path) -> dict[str, int]:
    """Walk ``repo_root/packages/{components,pages}/`` and write manifests.

    Skips ``_shared/`` (anything starting with ``_``).
    Returns a small counters dict for the caller to log.
    """
    pkgs = repo_root / "packages"
    counters = {"components_changed": 0, "pages_changed": 0,
                "components_seen": 0, "pages_seen": 0}
    if not pkgs.is_dir():
        return counters

    components_dir = pkgs / "components"
    if components_dir.is_dir():
        for child in sorted(components_dir.iterdir()):
            if not child.is_dir() or child.name.startswith("_"):
                continue
            counters["components_seen"] += 1
            if write_component(child):
                counters["components_changed"] += 1
                log.info("regenerated %s/package.json", child.relative_to(repo_root))

    pages_dir = pkgs / "pages"
    if pages_dir.is_dir():
        for child in sorted(pages_dir.iterdir()):
            if not child.is_dir() or child.name.startswith("_"):
                continue
            counters["pages_seen"] += 1
            if write_page(child):
                counters["pages_changed"] += 1
                log.info("regenerated %s/{package.json,vite.config.ts}",
                         child.relative_to(repo_root))

    return counters
